inertial_param:
    mass:
        m: 0.7
    MOI:
        Jxx: 1
        Jxy: 0
        Jxz: 0
        Jyy: 1
        Jyz: 0
        Jzz: 1
    offset:
        x: 0
        y: 0
        z: 0
aerodynamics_param:
    C_l: 1
    C_m: 1
length_param:
    l: 0.17