/* This file was automatically generated by CasADi 3.6.5.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Quadrotor_model_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

static const casadi_int casadi_s0[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {0, 0, 0};

static const casadi_real casadi_c0[3] = {0., 0., -9.8100000000000005e+00};

/* Quadrotor_model_expl_ode_fun:(i0[13],i1[4],i2[])->(o0[13]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real *w0=w+4, w1, w2, w3, w4, w5, w6, w7, *w8=w+14, *w9=w+17, w10, w11, *w12=w+23, *w13=w+27, *w14=w+31, *w15=w+35, *w16=w+39, *w17=w+55, *w18=w+71, *w19=w+74, *w20=w+77, *w21=w+80, *w22=w+83, *w23=w+92;
  /* #0: @0 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 3, w0);
  /* #1: output[0][0] = @0 */
  casadi_copy(w0, 3, res[0]);
  /* #2: @1 = 0 */
  w1 = 0.;
  /* #3: @2 = 0 */
  w2 = 0.;
  /* #4: @3 = input[1][0] */
  w3 = arg[1] ? arg[1][0] : 0;
  /* #5: @4 = input[1][1] */
  w4 = arg[1] ? arg[1][1] : 0;
  /* #6: @5 = (@3+@4) */
  w5  = (w3+w4);
  /* #7: @6 = input[1][2] */
  w6 = arg[1] ? arg[1][2] : 0;
  /* #8: @5 = (@5+@6) */
  w5 += w6;
  /* #9: @7 = input[1][3] */
  w7 = arg[1] ? arg[1][3] : 0;
  /* #10: @5 = (@5+@7) */
  w5 += w7;
  /* #11: @0 = vertcat(@1, @2, @5) */
  rr=w0;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w5;
  /* #12: @1 = 0.68 */
  w1 = 6.8000000000000005e-01;
  /* #13: @0 = (@0/@1) */
  for (i=0, rr=w0; i<3; ++i) (*rr++) /= w1;
  /* #14: @8 = [0, 0, -9.81] */
  casadi_copy(casadi_c0, 3, w8);
  /* #15: @0 = (@0-@8) */
  for (i=0, rr=w0, cs=w8; i<3; ++i) (*rr++) -= (*cs++);
  /* #16: output[0][1] = @0 */
  if (res[0]) casadi_copy(w0, 3, res[0]+3);
  /* #17: @1 = 0.5 */
  w1 = 5.0000000000000000e-01;
  /* #18: @9 = zeros(4x1) */
  casadi_clear(w9, 4);
  /* #19: @2 = 0 */
  w2 = 0.;
  /* #20: @0 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+10 : 0, 3, w0);
  /* #21: @5 = @0[0] */
  for (rr=(&w5), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #22: @5 = (-@5) */
  w5 = (- w5 );
  /* #23: @10 = @0[2] */
  for (rr=(&w10), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #24: @10 = (-@10) */
  w10 = (- w10 );
  /* #25: @11 = 0 */
  w11 = 0.;
  /* #26: @12 = horzcat(@2, @5, @10, @11) */
  rr=w12;
  *rr++ = w2;
  *rr++ = w5;
  *rr++ = w10;
  *rr++ = w11;
  /* #27: @12 = @12' */
  /* #28: @2 = @0[0] */
  for (rr=(&w2), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #29: @5 = 0 */
  w5 = 0.;
  /* #30: @10 = @0[2] */
  for (rr=(&w10), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #31: @10 = (-@10) */
  w10 = (- w10 );
  /* #32: @11 = @0[1] */
  for (rr=(&w11), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #33: @13 = horzcat(@2, @5, @10, @11) */
  rr=w13;
  *rr++ = w2;
  *rr++ = w5;
  *rr++ = w10;
  *rr++ = w11;
  /* #34: @13 = @13' */
  /* #35: @2 = @0[1] */
  for (rr=(&w2), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #36: @5 = 0 */
  w5 = 0.;
  /* #37: @10 = 0 */
  w10 = 0.;
  /* #38: @11 = @0[0] */
  for (rr=(&w11), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #39: @11 = (-@11) */
  w11 = (- w11 );
  /* #40: @14 = horzcat(@2, @5, @10, @11) */
  rr=w14;
  *rr++ = w2;
  *rr++ = w5;
  *rr++ = w10;
  *rr++ = w11;
  /* #41: @14 = @14' */
  /* #42: @2 = @0[2] */
  for (rr=(&w2), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #43: @5 = @0[1] */
  for (rr=(&w5), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #44: @5 = (-@5) */
  w5 = (- w5 );
  /* #45: @10 = @0[0] */
  for (rr=(&w10), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #46: @11 = 0 */
  w11 = 0.;
  /* #47: @15 = horzcat(@2, @5, @10, @11) */
  rr=w15;
  *rr++ = w2;
  *rr++ = w5;
  *rr++ = w10;
  *rr++ = w11;
  /* #48: @15 = @15' */
  /* #49: @16 = horzcat(@12, @13, @14, @15) */
  rr=w16;
  for (i=0, cs=w12; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  /* #50: @17 = @16' */
  for (i=0, rr=w17, cs=w16; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #51: @12 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+6 : 0, 4, w12);
  /* #52: @9 = mac(@17,@12,@9) */
  for (i=0, rr=w9; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w17+j, tt=w12+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #53: @9 = (@1*@9) */
  for (i=0, rr=w9, cs=w9; i<4; ++i) (*rr++)  = (w1*(*cs++));
  /* #54: output[0][2] = @9 */
  if (res[0]) casadi_copy(w9, 4, res[0]+6);
  /* #55: @1 = 142.857 */
  w1 = 1.4285714285714286e+02;
  /* #56: @2 = 0.2 */
  w2 = 2.0000000000000001e-01;
  /* #57: @5 = (@4-@7) */
  w5  = (w4-w7);
  /* #58: @2 = (@2*@5) */
  w2 *= w5;
  /* #59: @5 = 0.2 */
  w5 = 2.0000000000000001e-01;
  /* #60: @10 = (@6-@3) */
  w10  = (w6-w3);
  /* #61: @5 = (@5*@10) */
  w5 *= w10;
  /* #62: @3 = (@3-@4) */
  w3 -= w4;
  /* #63: @3 = (@3+@6) */
  w3 += w6;
  /* #64: @3 = (@3-@7) */
  w3 -= w7;
  /* #65: @8 = vertcat(@2, @5, @3) */
  rr=w8;
  *rr++ = w2;
  *rr++ = w5;
  *rr++ = w3;
  /* #66: @18 = zeros(3x1) */
  casadi_clear(w18, 3);
  /* #67: @2 = 0 */
  w2 = 0.;
  /* #68: @5 = @0[2] */
  for (rr=(&w5), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #69: @5 = (-@5) */
  w5 = (- w5 );
  /* #70: @3 = @0[1] */
  for (rr=(&w3), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #71: @19 = horzcat(@2, @5, @3) */
  rr=w19;
  *rr++ = w2;
  *rr++ = w5;
  *rr++ = w3;
  /* #72: @19 = @19' */
  /* #73: @2 = @0[2] */
  for (rr=(&w2), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #74: @5 = 0 */
  w5 = 0.;
  /* #75: @3 = @0[0] */
  for (rr=(&w3), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #76: @3 = (-@3) */
  w3 = (- w3 );
  /* #77: @20 = horzcat(@2, @5, @3) */
  rr=w20;
  *rr++ = w2;
  *rr++ = w5;
  *rr++ = w3;
  /* #78: @20 = @20' */
  /* #79: @2 = @0[1] */
  for (rr=(&w2), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #80: @2 = (-@2) */
  w2 = (- w2 );
  /* #81: @5 = @0[0] */
  for (rr=(&w5), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #82: @3 = 0 */
  w3 = 0.;
  /* #83: @21 = horzcat(@2, @5, @3) */
  rr=w21;
  *rr++ = w2;
  *rr++ = w5;
  *rr++ = w3;
  /* #84: @21 = @21' */
  /* #85: @22 = horzcat(@19, @20, @21) */
  rr=w22;
  for (i=0, cs=w19; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<3; ++i) *rr++ = *cs++;
  /* #86: @23 = @22' */
  for (i=0, rr=w23, cs=w22; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #87: @2 = 0.007 */
  w2 = 7.0000000000000001e-03;
  /* #88: @5 = @0[0] */
  for (rr=(&w5), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #89: @2 = (@2*@5) */
  w2 *= w5;
  /* #90: @5 = 0.007 */
  w5 = 7.0000000000000001e-03;
  /* #91: @3 = @0[1] */
  for (rr=(&w3), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #92: @5 = (@5*@3) */
  w5 *= w3;
  /* #93: @3 = 0.012 */
  w3 = 1.2000000000000000e-02;
  /* #94: @7 = @0[2] */
  for (rr=(&w7), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #95: @3 = (@3*@7) */
  w3 *= w7;
  /* #96: @0 = vertcat(@2, @5, @3) */
  rr=w0;
  *rr++ = w2;
  *rr++ = w5;
  *rr++ = w3;
  /* #97: @18 = mac(@23,@0,@18) */
  for (i=0, rr=w18; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w23+j, tt=w0+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #98: @8 = (@8-@18) */
  for (i=0, rr=w8, cs=w18; i<3; ++i) (*rr++) -= (*cs++);
  /* #99: @2 = @8[0] */
  for (rr=(&w2), ss=w8+0; ss!=w8+1; ss+=1) *rr++ = *ss;
  /* #100: @1 = (@1*@2) */
  w1 *= w2;
  /* #101: output[0][3] = @1 */
  if (res[0]) res[0][10] = w1;
  /* #102: @1 = 142.857 */
  w1 = 1.4285714285714286e+02;
  /* #103: @2 = @8[1] */
  for (rr=(&w2), ss=w8+1; ss!=w8+2; ss+=1) *rr++ = *ss;
  /* #104: @1 = (@1*@2) */
  w1 *= w2;
  /* #105: output[0][4] = @1 */
  if (res[0]) res[0][11] = w1;
  /* #106: @1 = 83.3333 */
  w1 = 8.3333333333333329e+01;
  /* #107: @2 = @8[2] */
  for (rr=(&w2), ss=w8+2; ss!=w8+3; ss+=1) *rr++ = *ss;
  /* #108: @1 = (@1*@2) */
  w1 *= w2;
  /* #109: output[0][5] = @1 */
  if (res[0]) res[0][12] = w1;
  return 0;
}

CASADI_SYMBOL_EXPORT int Quadrotor_model_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Quadrotor_model_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Quadrotor_model_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Quadrotor_model_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Quadrotor_model_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Quadrotor_model_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Quadrotor_model_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void Quadrotor_model_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Quadrotor_model_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int Quadrotor_model_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Quadrotor_model_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Quadrotor_model_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Quadrotor_model_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Quadrotor_model_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Quadrotor_model_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Quadrotor_model_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 101;
  return 0;
}

CASADI_SYMBOL_EXPORT int Quadrotor_model_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 101*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
