/* This file was automatically generated by CasADi 3.6.5.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Quadrotor_model_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

static const casadi_int casadi_s0[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[18] = {17, 1, 0, 14, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};

/* Quadrotor_model_expl_vde_adj:(i0[13],i1[13],i2[4],i3[])->(o0[17x1,14nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real *w0=w+4, *w1=w+17, *w2=w+20, *w3=w+23, w4, w5, w6, *w7=w+30, w8, w9, w10, w11, *w12=w+38, *w13=w+42, *w14=w+46, *w15=w+50, *w16=w+54, *w17=w+70, *w18=w+73, *w19=w+76, *w20=w+79, *w21=w+82, *w22=w+85, *w23=w+94, *w24=w+103;
  /* #0: @0 = input[1][0] */
  casadi_copy(arg[1], 13, w0);
  /* #1: {@1, @2, @3, @4, @5, @6} = vertsplit(@0) */
  casadi_copy(w0, 3, w1);
  casadi_copy(w0+3, 3, w2);
  casadi_copy(w0+6, 4, w3);
  w4 = w0[10];
  w5 = w0[11];
  w6 = w0[12];
  /* #2: output[0][0] = @1 */
  casadi_copy(w1, 3, res[0]);
  /* #3: @7 = zeros(4x1) */
  casadi_clear(w7, 4);
  /* #4: @8 = 0 */
  w8 = 0.;
  /* #5: @1 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+10 : 0, 3, w1);
  /* #6: @9 = @1[0] */
  for (rr=(&w9), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #7: @9 = (-@9) */
  w9 = (- w9 );
  /* #8: @10 = @1[2] */
  for (rr=(&w10), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #9: @10 = (-@10) */
  w10 = (- w10 );
  /* #10: @11 = 0 */
  w11 = 0.;
  /* #11: @12 = horzcat(@8, @9, @10, @11) */
  rr=w12;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  /* #12: @12 = @12' */
  /* #13: @8 = @1[0] */
  for (rr=(&w8), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #14: @9 = 0 */
  w9 = 0.;
  /* #15: @10 = @1[2] */
  for (rr=(&w10), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #16: @10 = (-@10) */
  w10 = (- w10 );
  /* #17: @11 = @1[1] */
  for (rr=(&w11), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #18: @13 = horzcat(@8, @9, @10, @11) */
  rr=w13;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  /* #19: @13 = @13' */
  /* #20: @8 = @1[1] */
  for (rr=(&w8), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #21: @9 = 0 */
  w9 = 0.;
  /* #22: @10 = 0 */
  w10 = 0.;
  /* #23: @11 = @1[0] */
  for (rr=(&w11), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #24: @11 = (-@11) */
  w11 = (- w11 );
  /* #25: @14 = horzcat(@8, @9, @10, @11) */
  rr=w14;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  /* #26: @14 = @14' */
  /* #27: @8 = @1[2] */
  for (rr=(&w8), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #28: @9 = @1[1] */
  for (rr=(&w9), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #29: @9 = (-@9) */
  w9 = (- w9 );
  /* #30: @10 = @1[0] */
  for (rr=(&w10), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #31: @11 = 0 */
  w11 = 0.;
  /* #32: @15 = horzcat(@8, @9, @10, @11) */
  rr=w15;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  /* #33: @15 = @15' */
  /* #34: @16 = horzcat(@12, @13, @14, @15) */
  rr=w16;
  for (i=0, cs=w12; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  /* #35: @8 = 0.5 */
  w8 = 5.0000000000000000e-01;
  /* #36: @3 = (@8*@3) */
  for (i=0, rr=w3, cs=w3; i<4; ++i) (*rr++)  = (w8*(*cs++));
  /* #37: @7 = mac(@16,@3,@7) */
  for (i=0, rr=w7; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w16+j, tt=w3+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #38: output[0][1] = @7 */
  if (res[0]) casadi_copy(w7, 4, res[0]+3);
  /* #39: @17 = zeros(3x1) */
  casadi_clear(w17, 3);
  /* #40: @8 = 0.012 */
  w8 = 1.2000000000000000e-02;
  /* #41: @18 = zeros(3x1) */
  casadi_clear(w18, 3);
  /* #42: @9 = 0 */
  w9 = 0.;
  /* #43: @10 = @1[2] */
  for (rr=(&w10), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #44: @10 = (-@10) */
  w10 = (- w10 );
  /* #45: @11 = @1[1] */
  for (rr=(&w11), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #46: @19 = horzcat(@9, @10, @11) */
  rr=w19;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  /* #47: @19 = @19' */
  /* #48: @9 = @1[2] */
  for (rr=(&w9), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #49: @10 = 0 */
  w10 = 0.;
  /* #50: @11 = @1[0] */
  for (rr=(&w11), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #51: @11 = (-@11) */
  w11 = (- w11 );
  /* #52: @20 = horzcat(@9, @10, @11) */
  rr=w20;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  /* #53: @20 = @20' */
  /* #54: @9 = @1[1] */
  for (rr=(&w9), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #55: @9 = (-@9) */
  w9 = (- w9 );
  /* #56: @10 = @1[0] */
  for (rr=(&w10), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #57: @11 = 0 */
  w11 = 0.;
  /* #58: @21 = horzcat(@9, @10, @11) */
  rr=w21;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  /* #59: @21 = @21' */
  /* #60: @22 = horzcat(@19, @20, @21) */
  rr=w22;
  for (i=0, cs=w19; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<3; ++i) *rr++ = *cs++;
  /* #61: @19 = zeros(3x1) */
  casadi_clear(w19, 3);
  /* #62: @9 = 83.3333 */
  w9 = 8.3333333333333329e+01;
  /* #63: @9 = (@9*@6) */
  w9 *= w6;
  /* #64: (@19[2] += @9) */
  for (rr=w19+2, ss=(&w9); rr!=w19+3; rr+=1) *rr += *ss++;
  /* #65: @9 = 142.857 */
  w9 = 1.4285714285714286e+02;
  /* #66: @9 = (@9*@5) */
  w9 *= w5;
  /* #67: (@19[1] += @9) */
  for (rr=w19+1, ss=(&w9); rr!=w19+2; rr+=1) *rr += *ss++;
  /* #68: @9 = 142.857 */
  w9 = 1.4285714285714286e+02;
  /* #69: @9 = (@9*@4) */
  w9 *= w4;
  /* #70: (@19[0] += @9) */
  for (rr=w19+0, ss=(&w9); rr!=w19+1; rr+=1) *rr += *ss++;
  /* #71: @20 = (-@19) */
  for (i=0, rr=w20, cs=w19; i<3; ++i) *rr++ = (- *cs++ );
  /* #72: @18 = mac(@22,@20,@18) */
  for (i=0, rr=w18; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w22+j, tt=w20+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #73: {@9, @4, @5} = vertsplit(@18) */
  w9 = w18[0];
  w4 = w18[1];
  w5 = w18[2];
  /* #74: @5 = (@8*@5) */
  w5  = (w8*w5);
  /* #75: (@17[2] += @5) */
  for (rr=w17+2, ss=(&w5); rr!=w17+3; rr+=1) *rr += *ss++;
  /* #76: @5 = 0.007 */
  w5 = 7.0000000000000001e-03;
  /* #77: @4 = (@5*@4) */
  w4  = (w5*w4);
  /* #78: (@17[1] += @4) */
  for (rr=w17+1, ss=(&w4); rr!=w17+2; rr+=1) *rr += *ss++;
  /* #79: @4 = 0.007 */
  w4 = 7.0000000000000001e-03;
  /* #80: @9 = (@4*@9) */
  w9  = (w4*w9);
  /* #81: (@17[0] += @9) */
  for (rr=w17+0, ss=(&w9); rr!=w17+1; rr+=1) *rr += *ss++;
  /* #82: @22 = zeros(3x3) */
  casadi_clear(w22, 9);
  /* #83: @9 = @1[0] */
  for (rr=(&w9), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #84: @4 = (@4*@9) */
  w4 *= w9;
  /* #85: @9 = @1[1] */
  for (rr=(&w9), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #86: @5 = (@5*@9) */
  w5 *= w9;
  /* #87: @9 = @1[2] */
  for (rr=(&w9), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #88: @8 = (@8*@9) */
  w8 *= w9;
  /* #89: @1 = vertcat(@4, @5, @8) */
  rr=w1;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w8;
  /* #90: @1 = @1' */
  /* #91: @22 = mac(@20,@1,@22) */
  for (i=0, rr=w22; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w20+j, tt=w1+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #92: @23 = @22' */
  for (i=0, rr=w23, cs=w22; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #93: {@20, @1, @18} = horzsplit(@23) */
  casadi_copy(w23, 3, w20);
  casadi_copy(w23+3, 3, w1);
  casadi_copy(w23+6, 3, w18);
  /* #94: @18 = @18' */
  /* #95: {@4, @5, NULL} = horzsplit(@18) */
  w4 = w18[0];
  w5 = w18[1];
  /* #96: (@17[0] += @5) */
  for (rr=w17+0, ss=(&w5); rr!=w17+1; rr+=1) *rr += *ss++;
  /* #97: @4 = (-@4) */
  w4 = (- w4 );
  /* #98: (@17[1] += @4) */
  for (rr=w17+1, ss=(&w4); rr!=w17+2; rr+=1) *rr += *ss++;
  /* #99: @1 = @1' */
  /* #100: {@4, NULL, @5} = horzsplit(@1) */
  w4 = w1[0];
  w5 = w1[2];
  /* #101: @5 = (-@5) */
  w5 = (- w5 );
  /* #102: (@17[0] += @5) */
  for (rr=w17+0, ss=(&w5); rr!=w17+1; rr+=1) *rr += *ss++;
  /* #103: (@17[2] += @4) */
  for (rr=w17+2, ss=(&w4); rr!=w17+3; rr+=1) *rr += *ss++;
  /* #104: @20 = @20' */
  /* #105: {NULL, @4, @5} = horzsplit(@20) */
  w4 = w20[1];
  w5 = w20[2];
  /* #106: (@17[1] += @5) */
  for (rr=w17+1, ss=(&w5); rr!=w17+2; rr+=1) *rr += *ss++;
  /* #107: @4 = (-@4) */
  w4 = (- w4 );
  /* #108: (@17[2] += @4) */
  for (rr=w17+2, ss=(&w4); rr!=w17+3; rr+=1) *rr += *ss++;
  /* #109: @16 = zeros(4x4) */
  casadi_clear(w16, 16);
  /* #110: @7 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+6 : 0, 4, w7);
  /* #111: @7 = @7' */
  /* #112: @16 = mac(@3,@7,@16) */
  for (i=0, rr=w16; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w3+j, tt=w7+i*1; k<1; ++k) *rr += ss[k*4]**tt++;
  /* #113: @24 = @16' */
  for (i=0, rr=w24, cs=w16; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #114: {@3, @7, @12, @13} = horzsplit(@24) */
  casadi_copy(w24, 4, w3);
  casadi_copy(w24+4, 4, w7);
  casadi_copy(w24+8, 4, w12);
  casadi_copy(w24+12, 4, w13);
  /* #115: @13 = @13' */
  /* #116: {@4, @5, @8, NULL} = horzsplit(@13) */
  w4 = w13[0];
  w5 = w13[1];
  w8 = w13[2];
  /* #117: (@17[0] += @8) */
  for (rr=w17+0, ss=(&w8); rr!=w17+1; rr+=1) *rr += *ss++;
  /* #118: @5 = (-@5) */
  w5 = (- w5 );
  /* #119: (@17[1] += @5) */
  for (rr=w17+1, ss=(&w5); rr!=w17+2; rr+=1) *rr += *ss++;
  /* #120: (@17[2] += @4) */
  for (rr=w17+2, ss=(&w4); rr!=w17+3; rr+=1) *rr += *ss++;
  /* #121: @12 = @12' */
  /* #122: {@4, NULL, NULL, @5} = horzsplit(@12) */
  w4 = w12[0];
  w5 = w12[3];
  /* #123: @5 = (-@5) */
  w5 = (- w5 );
  /* #124: (@17[0] += @5) */
  for (rr=w17+0, ss=(&w5); rr!=w17+1; rr+=1) *rr += *ss++;
  /* #125: (@17[1] += @4) */
  for (rr=w17+1, ss=(&w4); rr!=w17+2; rr+=1) *rr += *ss++;
  /* #126: @7 = @7' */
  /* #127: {@4, NULL, @5, @8} = horzsplit(@7) */
  w4 = w7[0];
  w5 = w7[2];
  w8 = w7[3];
  /* #128: (@17[1] += @8) */
  for (rr=w17+1, ss=(&w8); rr!=w17+2; rr+=1) *rr += *ss++;
  /* #129: @5 = (-@5) */
  w5 = (- w5 );
  /* #130: (@17[2] += @5) */
  for (rr=w17+2, ss=(&w5); rr!=w17+3; rr+=1) *rr += *ss++;
  /* #131: (@17[0] += @4) */
  for (rr=w17+0, ss=(&w4); rr!=w17+1; rr+=1) *rr += *ss++;
  /* #132: @3 = @3' */
  /* #133: {NULL, @4, @5, NULL} = horzsplit(@3) */
  w4 = w3[1];
  w5 = w3[2];
  /* #134: @5 = (-@5) */
  w5 = (- w5 );
  /* #135: (@17[2] += @5) */
  for (rr=w17+2, ss=(&w5); rr!=w17+3; rr+=1) *rr += *ss++;
  /* #136: @4 = (-@4) */
  w4 = (- w4 );
  /* #137: (@17[0] += @4) */
  for (rr=w17+0, ss=(&w4); rr!=w17+1; rr+=1) *rr += *ss++;
  /* #138: output[0][2] = @17 */
  if (res[0]) casadi_copy(w17, 3, res[0]+7);
  /* #139: {@4, @5, @8} = vertsplit(@19) */
  w4 = w19[0];
  w5 = w19[1];
  w8 = w19[2];
  /* #140: @9 = 0.2 */
  w9 = 2.0000000000000001e-01;
  /* #141: @9 = (@9*@5) */
  w9 *= w5;
  /* #142: @5 = (@8-@9) */
  w5  = (w8-w9);
  /* #143: @6 = 1.47059 */
  w6 = 1.4705882352941175e+00;
  /* #144: @2 = (@6*@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) (*rr++)  = (w6*(*cs++));
  /* #145: {NULL, NULL, @6} = vertsplit(@2) */
  w6 = w2[2];
  /* #146: @5 = (@5+@6) */
  w5 += w6;
  /* #147: output[0][3] = @5 */
  if (res[0]) res[0][10] = w5;
  /* #148: @5 = 0.2 */
  w5 = 2.0000000000000001e-01;
  /* #149: @5 = (@5*@4) */
  w5 *= w4;
  /* #150: @4 = (@5-@8) */
  w4  = (w5-w8);
  /* #151: @4 = (@4+@6) */
  w4 += w6;
  /* #152: output[0][4] = @4 */
  if (res[0]) res[0][11] = w4;
  /* #153: @9 = (@8+@9) */
  w9  = (w8+w9);
  /* #154: @9 = (@9+@6) */
  w9 += w6;
  /* #155: output[0][5] = @9 */
  if (res[0]) res[0][12] = w9;
  /* #156: @5 = (-@5) */
  w5 = (- w5 );
  /* #157: @5 = (@5-@8) */
  w5 -= w8;
  /* #158: @5 = (@5+@6) */
  w5 += w6;
  /* #159: output[0][6] = @5 */
  if (res[0]) res[0][13] = w5;
  return 0;
}

CASADI_SYMBOL_EXPORT int Quadrotor_model_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Quadrotor_model_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Quadrotor_model_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Quadrotor_model_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Quadrotor_model_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Quadrotor_model_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Quadrotor_model_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void Quadrotor_model_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Quadrotor_model_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Quadrotor_model_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Quadrotor_model_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Quadrotor_model_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Quadrotor_model_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Quadrotor_model_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Quadrotor_model_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Quadrotor_model_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 7;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 119;
  return 0;
}

CASADI_SYMBOL_EXPORT int Quadrotor_model_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 7*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 119*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
