/* This file was automatically generated by CasADi 3.6.5.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Quadrotor_model_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[18] = {17, 1, 0, 14, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};

/* Quadrotor_model_expl_vde_adj:(i0[13],i1[13],i2[4],i3[])->(o0[17x1,14nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real *w0=w+4, *w1=w+17, *w2=w+20, *w3=w+23, w4, w5, w6, *w7=w+30, w8, w9, w10, w11, *w12=w+38, *w13=w+42, *w14=w+46, *w15=w+50, *w16=w+54, *w17=w+70, w18, w19, *w20=w+81, *w21=w+84, *w22=w+93, *w23=w+96, w24, w25, w26, w27, w28, w29, w30, w31, w32, w33, w34, w35, w36, w37, w38, w39, w40, w41, w42, w43, w44, w45, w46, w47, w48, w49, w50, w51, *w52=w+127, *w53=w+130, *w54=w+133;
  /* #0: @0 = input[1][0] */
  casadi_copy(arg[1], 13, w0);
  /* #1: {@1, @2, @3, @4, @5, @6} = vertsplit(@0) */
  casadi_copy(w0, 3, w1);
  casadi_copy(w0+3, 3, w2);
  casadi_copy(w0+6, 4, w3);
  w4 = w0[10];
  w5 = w0[11];
  w6 = w0[12];
  /* #2: output[0][0] = @1 */
  casadi_copy(w1, 3, res[0]);
  /* #3: @7 = zeros(4x1) */
  casadi_clear(w7, 4);
  /* #4: @8 = 0 */
  w8 = 0.;
  /* #5: @1 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+10 : 0, 3, w1);
  /* #6: @9 = @1[0] */
  for (rr=(&w9), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #7: @9 = (-@9) */
  w9 = (- w9 );
  /* #8: @10 = @1[2] */
  for (rr=(&w10), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #9: @10 = (-@10) */
  w10 = (- w10 );
  /* #10: @11 = 0 */
  w11 = 0.;
  /* #11: @12 = horzcat(@8, @9, @10, @11) */
  rr=w12;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  /* #12: @12 = @12' */
  /* #13: @8 = @1[0] */
  for (rr=(&w8), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #14: @9 = 0 */
  w9 = 0.;
  /* #15: @10 = @1[2] */
  for (rr=(&w10), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #16: @10 = (-@10) */
  w10 = (- w10 );
  /* #17: @11 = @1[1] */
  for (rr=(&w11), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #18: @13 = horzcat(@8, @9, @10, @11) */
  rr=w13;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  /* #19: @13 = @13' */
  /* #20: @8 = @1[1] */
  for (rr=(&w8), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #21: @9 = @1[2] */
  for (rr=(&w9), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #22: @10 = 0 */
  w10 = 0.;
  /* #23: @11 = @1[0] */
  for (rr=(&w11), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #24: @11 = (-@11) */
  w11 = (- w11 );
  /* #25: @14 = horzcat(@8, @9, @10, @11) */
  rr=w14;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  /* #26: @14 = @14' */
  /* #27: @8 = @1[2] */
  for (rr=(&w8), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #28: @9 = @1[1] */
  for (rr=(&w9), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #29: @9 = (-@9) */
  w9 = (- w9 );
  /* #30: @10 = @1[0] */
  for (rr=(&w10), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #31: @11 = 0 */
  w11 = 0.;
  /* #32: @15 = horzcat(@8, @9, @10, @11) */
  rr=w15;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  /* #33: @15 = @15' */
  /* #34: @16 = horzcat(@12, @13, @14, @15) */
  rr=w16;
  for (i=0, cs=w12; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  /* #35: @8 = 0.5 */
  w8 = 5.0000000000000000e-01;
  /* #36: @3 = (@8*@3) */
  for (i=0, rr=w3, cs=w3; i<4; ++i) (*rr++)  = (w8*(*cs++));
  /* #37: @7 = mac(@16,@3,@7) */
  for (i=0, rr=w7; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w16+j, tt=w3+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #38: @12 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+6 : 0, 4, w12);
  /* #39: @8 = @12[1] */
  for (rr=(&w8), ss=w12+1; ss!=w12+2; ss+=1) *rr++ = *ss;
  /* #40: @9 = (2.*@8) */
  w9 = (2.* w8 );
  /* #41: @17 = zeros(3x3) */
  casadi_clear(w17, 9);
  /* #42: @10 = 0 */
  w10 = 0.;
  /* #43: @11 = 0 */
  w11 = 0.;
  /* #44: @18 = input[2][0] */
  w18 = arg[2] ? arg[2][0] : 0;
  /* #45: @19 = input[2][1] */
  w19 = arg[2] ? arg[2][1] : 0;
  /* #46: @18 = (@18+@19) */
  w18 += w19;
  /* #47: @19 = input[2][2] */
  w19 = arg[2] ? arg[2][2] : 0;
  /* #48: @18 = (@18+@19) */
  w18 += w19;
  /* #49: @19 = input[2][3] */
  w19 = arg[2] ? arg[2][3] : 0;
  /* #50: @18 = (@18+@19) */
  w18 += w19;
  /* #51: @20 = vertcat(@10, @11, @18) */
  rr=w20;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w18;
  /* #52: @10 = 0.68 */
  w10 = 6.8000000000000005e-01;
  /* #53: @20 = (@20/@10) */
  for (i=0, rr=w20; i<3; ++i) (*rr++) /= w10;
  /* #54: @20 = @20' */
  /* #55: @17 = mac(@2,@20,@17) */
  for (i=0, rr=w17; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w2+j, tt=w20+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #56: @21 = @17' */
  for (i=0, rr=w21, cs=w17; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #57: {@20, @22, @23} = horzsplit(@21) */
  casadi_copy(w21, 3, w20);
  casadi_copy(w21+3, 3, w22);
  casadi_copy(w21+6, 3, w23);
  /* #58: @23 = @23' */
  /* #59: {@10, @11, @18} = horzsplit(@23) */
  w10 = w23[0];
  w11 = w23[1];
  w18 = w23[2];
  /* #60: @18 = (-@18) */
  w18 = (- w18 );
  /* #61: @18 = (2.*@18) */
  w18 = (2.* w18 );
  /* #62: @9 = (@9*@18) */
  w9 *= w18;
  /* #63: (@7[1] += @9) */
  for (rr=w7+1, ss=(&w9); rr!=w7+2; rr+=1) *rr += *ss++;
  /* #64: @9 = @12[0] */
  for (rr=(&w9), ss=w12+0; ss!=w12+1; ss+=1) *rr++ = *ss;
  /* #65: @19 = (2.*@9) */
  w19 = (2.* w9 );
  /* #66: @19 = (@19*@18) */
  w19 *= w18;
  /* #67: (@7[0] += @19) */
  for (rr=w7+0, ss=(&w19); rr!=w7+1; rr+=1) *rr += *ss++;
  /* #68: @19 = @12[3] */
  for (rr=(&w19), ss=w12+3; ss!=w12+4; ss+=1) *rr++ = *ss;
  /* #69: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #70: @18 = (@19*@11) */
  w18  = (w19*w11);
  /* #71: (@7[0] += @18) */
  for (rr=w7+0, ss=(&w18); rr!=w7+1; rr+=1) *rr += *ss++;
  /* #72: @18 = @12[0] */
  for (rr=(&w18), ss=w12+0; ss!=w12+1; ss+=1) *rr++ = *ss;
  /* #73: @24 = (@18*@11) */
  w24  = (w18*w11);
  /* #74: (@7[3] += @24) */
  for (rr=w7+3, ss=(&w24); rr!=w7+4; rr+=1) *rr += *ss++;
  /* #75: @24 = @12[1] */
  for (rr=(&w24), ss=w12+1; ss!=w12+2; ss+=1) *rr++ = *ss;
  /* #76: @25 = (@24*@11) */
  w25  = (w24*w11);
  /* #77: (@7[2] += @25) */
  for (rr=w7+2, ss=(&w25); rr!=w7+3; rr+=1) *rr += *ss++;
  /* #78: @25 = @12[2] */
  for (rr=(&w25), ss=w12+2; ss!=w12+3; ss+=1) *rr++ = *ss;
  /* #79: @11 = (@25*@11) */
  w11  = (w25*w11);
  /* #80: (@7[1] += @11) */
  for (rr=w7+1, ss=(&w11); rr!=w7+2; rr+=1) *rr += *ss++;
  /* #81: @11 = @12[3] */
  for (rr=(&w11), ss=w12+3; ss!=w12+4; ss+=1) *rr++ = *ss;
  /* #82: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #83: @26 = (@11*@10) */
  w26  = (w11*w10);
  /* #84: @26 = (-@26) */
  w26 = (- w26 );
  /* #85: (@7[1] += @26) */
  for (rr=w7+1, ss=(&w26); rr!=w7+2; rr+=1) *rr += *ss++;
  /* #86: @26 = @12[1] */
  for (rr=(&w26), ss=w12+1; ss!=w12+2; ss+=1) *rr++ = *ss;
  /* #87: @27 = (@26*@10) */
  w27  = (w26*w10);
  /* #88: @27 = (-@27) */
  w27 = (- w27 );
  /* #89: (@7[3] += @27) */
  for (rr=w7+3, ss=(&w27); rr!=w7+4; rr+=1) *rr += *ss++;
  /* #90: @27 = @12[0] */
  for (rr=(&w27), ss=w12+0; ss!=w12+1; ss+=1) *rr++ = *ss;
  /* #91: @28 = (@27*@10) */
  w28  = (w27*w10);
  /* #92: (@7[2] += @28) */
  for (rr=w7+2, ss=(&w28); rr!=w7+3; rr+=1) *rr += *ss++;
  /* #93: @28 = @12[2] */
  for (rr=(&w28), ss=w12+2; ss!=w12+3; ss+=1) *rr++ = *ss;
  /* #94: @10 = (@28*@10) */
  w10  = (w28*w10);
  /* #95: (@7[0] += @10) */
  for (rr=w7+0, ss=(&w10); rr!=w7+1; rr+=1) *rr += *ss++;
  /* #96: @10 = @12[3] */
  for (rr=(&w10), ss=w12+3; ss!=w12+4; ss+=1) *rr++ = *ss;
  /* #97: @22 = @22' */
  /* #98: {@29, @30, @31} = horzsplit(@22) */
  w29 = w22[0];
  w30 = w22[1];
  w31 = w22[2];
  /* #99: @31 = (2.*@31) */
  w31 = (2.* w31 );
  /* #100: @32 = (@10*@31) */
  w32  = (w10*w31);
  /* #101: @32 = (-@32) */
  w32 = (- w32 );
  /* #102: (@7[0] += @32) */
  for (rr=w7+0, ss=(&w32); rr!=w7+1; rr+=1) *rr += *ss++;
  /* #103: @32 = @12[0] */
  for (rr=(&w32), ss=w12+0; ss!=w12+1; ss+=1) *rr++ = *ss;
  /* #104: @33 = (@32*@31) */
  w33  = (w32*w31);
  /* #105: @33 = (-@33) */
  w33 = (- w33 );
  /* #106: (@7[3] += @33) */
  for (rr=w7+3, ss=(&w33); rr!=w7+4; rr+=1) *rr += *ss++;
  /* #107: @33 = @12[1] */
  for (rr=(&w33), ss=w12+1; ss!=w12+2; ss+=1) *rr++ = *ss;
  /* #108: @34 = (@33*@31) */
  w34  = (w33*w31);
  /* #109: (@7[2] += @34) */
  for (rr=w7+2, ss=(&w34); rr!=w7+3; rr+=1) *rr += *ss++;
  /* #110: @34 = @12[2] */
  for (rr=(&w34), ss=w12+2; ss!=w12+3; ss+=1) *rr++ = *ss;
  /* #111: @31 = (@34*@31) */
  w31  = (w34*w31);
  /* #112: (@7[1] += @31) */
  for (rr=w7+1, ss=(&w31); rr!=w7+2; rr+=1) *rr += *ss++;
  /* #113: @31 = @12[2] */
  for (rr=(&w31), ss=w12+2; ss!=w12+3; ss+=1) *rr++ = *ss;
  /* #114: @35 = (2.*@31) */
  w35 = (2.* w31 );
  /* #115: @30 = (-@30) */
  w30 = (- w30 );
  /* #116: @30 = (2.*@30) */
  w30 = (2.* w30 );
  /* #117: @35 = (@35*@30) */
  w35 *= w30;
  /* #118: (@7[2] += @35) */
  for (rr=w7+2, ss=(&w35); rr!=w7+3; rr+=1) *rr += *ss++;
  /* #119: @35 = @12[0] */
  for (rr=(&w35), ss=w12+0; ss!=w12+1; ss+=1) *rr++ = *ss;
  /* #120: @36 = (2.*@35) */
  w36 = (2.* w35 );
  /* #121: @36 = (@36*@30) */
  w36 *= w30;
  /* #122: (@7[0] += @36) */
  for (rr=w7+0, ss=(&w36); rr!=w7+1; rr+=1) *rr += *ss++;
  /* #123: @36 = @12[3] */
  for (rr=(&w36), ss=w12+3; ss!=w12+4; ss+=1) *rr++ = *ss;
  /* #124: @29 = (2.*@29) */
  w29 = (2.* w29 );
  /* #125: @30 = (@36*@29) */
  w30  = (w36*w29);
  /* #126: (@7[2] += @30) */
  for (rr=w7+2, ss=(&w30); rr!=w7+3; rr+=1) *rr += *ss++;
  /* #127: @30 = @12[2] */
  for (rr=(&w30), ss=w12+2; ss!=w12+3; ss+=1) *rr++ = *ss;
  /* #128: @37 = (@30*@29) */
  w37  = (w30*w29);
  /* #129: (@7[3] += @37) */
  for (rr=w7+3, ss=(&w37); rr!=w7+4; rr+=1) *rr += *ss++;
  /* #130: @37 = @12[0] */
  for (rr=(&w37), ss=w12+0; ss!=w12+1; ss+=1) *rr++ = *ss;
  /* #131: @38 = (@37*@29) */
  w38  = (w37*w29);
  /* #132: (@7[1] += @38) */
  for (rr=w7+1, ss=(&w38); rr!=w7+2; rr+=1) *rr += *ss++;
  /* #133: @38 = @12[1] */
  for (rr=(&w38), ss=w12+1; ss!=w12+2; ss+=1) *rr++ = *ss;
  /* #134: @29 = (@38*@29) */
  w29  = (w38*w29);
  /* #135: (@7[0] += @29) */
  for (rr=w7+0, ss=(&w29); rr!=w7+1; rr+=1) *rr += *ss++;
  /* #136: @29 = @12[3] */
  for (rr=(&w29), ss=w12+3; ss!=w12+4; ss+=1) *rr++ = *ss;
  /* #137: @20 = @20' */
  /* #138: {@39, @40, @41} = horzsplit(@20) */
  w39 = w20[0];
  w40 = w20[1];
  w41 = w20[2];
  /* #139: @41 = (2.*@41) */
  w41 = (2.* w41 );
  /* #140: @42 = (@29*@41) */
  w42  = (w29*w41);
  /* #141: (@7[1] += @42) */
  for (rr=w7+1, ss=(&w42); rr!=w7+2; rr+=1) *rr += *ss++;
  /* #142: @42 = @12[1] */
  for (rr=(&w42), ss=w12+1; ss!=w12+2; ss+=1) *rr++ = *ss;
  /* #143: @43 = (@42*@41) */
  w43  = (w42*w41);
  /* #144: (@7[3] += @43) */
  for (rr=w7+3, ss=(&w43); rr!=w7+4; rr+=1) *rr += *ss++;
  /* #145: @43 = @12[0] */
  for (rr=(&w43), ss=w12+0; ss!=w12+1; ss+=1) *rr++ = *ss;
  /* #146: @44 = (@43*@41) */
  w44  = (w43*w41);
  /* #147: (@7[2] += @44) */
  for (rr=w7+2, ss=(&w44); rr!=w7+3; rr+=1) *rr += *ss++;
  /* #148: @44 = @12[2] */
  for (rr=(&w44), ss=w12+2; ss!=w12+3; ss+=1) *rr++ = *ss;
  /* #149: @41 = (@44*@41) */
  w41  = (w44*w41);
  /* #150: (@7[0] += @41) */
  for (rr=w7+0, ss=(&w41); rr!=w7+1; rr+=1) *rr += *ss++;
  /* #151: @41 = @12[3] */
  for (rr=(&w41), ss=w12+3; ss!=w12+4; ss+=1) *rr++ = *ss;
  /* #152: @40 = (2.*@40) */
  w40 = (2.* w40 );
  /* #153: @45 = (@41*@40) */
  w45  = (w41*w40);
  /* #154: @45 = (-@45) */
  w45 = (- w45 );
  /* #155: (@7[2] += @45) */
  for (rr=w7+2, ss=(&w45); rr!=w7+3; rr+=1) *rr += *ss++;
  /* #156: @45 = @12[2] */
  for (rr=(&w45), ss=w12+2; ss!=w12+3; ss+=1) *rr++ = *ss;
  /* #157: @46 = (@45*@40) */
  w46  = (w45*w40);
  /* #158: @46 = (-@46) */
  w46 = (- w46 );
  /* #159: (@7[3] += @46) */
  for (rr=w7+3, ss=(&w46); rr!=w7+4; rr+=1) *rr += *ss++;
  /* #160: @46 = @12[0] */
  for (rr=(&w46), ss=w12+0; ss!=w12+1; ss+=1) *rr++ = *ss;
  /* #161: @47 = (@46*@40) */
  w47  = (w46*w40);
  /* #162: (@7[1] += @47) */
  for (rr=w7+1, ss=(&w47); rr!=w7+2; rr+=1) *rr += *ss++;
  /* #163: @47 = @12[1] */
  for (rr=(&w47), ss=w12+1; ss!=w12+2; ss+=1) *rr++ = *ss;
  /* #164: @40 = (@47*@40) */
  w40  = (w47*w40);
  /* #165: (@7[0] += @40) */
  for (rr=w7+0, ss=(&w40); rr!=w7+1; rr+=1) *rr += *ss++;
  /* #166: @40 = @12[2] */
  for (rr=(&w40), ss=w12+2; ss!=w12+3; ss+=1) *rr++ = *ss;
  /* #167: @48 = (2.*@40) */
  w48 = (2.* w40 );
  /* #168: @39 = (-@39) */
  w39 = (- w39 );
  /* #169: @39 = (2.*@39) */
  w39 = (2.* w39 );
  /* #170: @48 = (@48*@39) */
  w48 *= w39;
  /* #171: (@7[2] += @48) */
  for (rr=w7+2, ss=(&w48); rr!=w7+3; rr+=1) *rr += *ss++;
  /* #172: @48 = @12[1] */
  for (rr=(&w48), ss=w12+1; ss!=w12+2; ss+=1) *rr++ = *ss;
  /* #173: @49 = (2.*@48) */
  w49 = (2.* w48 );
  /* #174: @49 = (@49*@39) */
  w49 *= w39;
  /* #175: (@7[1] += @49) */
  for (rr=w7+1, ss=(&w49); rr!=w7+2; rr+=1) *rr += *ss++;
  /* #176: output[0][1] = @7 */
  if (res[0]) casadi_copy(w7, 4, res[0]+3);
  /* #177: @20 = zeros(3x1) */
  casadi_clear(w20, 3);
  /* #178: @49 = 0.012 */
  w49 = 1.2000000000000000e-02;
  /* #179: @22 = zeros(3x1) */
  casadi_clear(w22, 3);
  /* #180: @39 = 0 */
  w39 = 0.;
  /* #181: @50 = @1[2] */
  for (rr=(&w50), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #182: @50 = (-@50) */
  w50 = (- w50 );
  /* #183: @51 = @1[1] */
  for (rr=(&w51), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #184: @23 = horzcat(@39, @50, @51) */
  rr=w23;
  *rr++ = w39;
  *rr++ = w50;
  *rr++ = w51;
  /* #185: @23 = @23' */
  /* #186: @39 = @1[2] */
  for (rr=(&w39), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #187: @50 = 0 */
  w50 = 0.;
  /* #188: @51 = @1[0] */
  for (rr=(&w51), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #189: @51 = (-@51) */
  w51 = (- w51 );
  /* #190: @52 = horzcat(@39, @50, @51) */
  rr=w52;
  *rr++ = w39;
  *rr++ = w50;
  *rr++ = w51;
  /* #191: @52 = @52' */
  /* #192: @39 = @1[1] */
  for (rr=(&w39), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #193: @39 = (-@39) */
  w39 = (- w39 );
  /* #194: @50 = @1[0] */
  for (rr=(&w50), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #195: @51 = 0 */
  w51 = 0.;
  /* #196: @53 = horzcat(@39, @50, @51) */
  rr=w53;
  *rr++ = w39;
  *rr++ = w50;
  *rr++ = w51;
  /* #197: @53 = @53' */
  /* #198: @21 = horzcat(@23, @52, @53) */
  rr=w21;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w52; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w53; i<3; ++i) *rr++ = *cs++;
  /* #199: @23 = zeros(3x1) */
  casadi_clear(w23, 3);
  /* #200: @39 = 83.3333 */
  w39 = 8.3333333333333329e+01;
  /* #201: @39 = (@39*@6) */
  w39 *= w6;
  /* #202: (@23[2] += @39) */
  for (rr=w23+2, ss=(&w39); rr!=w23+3; rr+=1) *rr += *ss++;
  /* #203: @39 = 142.857 */
  w39 = 1.4285714285714286e+02;
  /* #204: @39 = (@39*@5) */
  w39 *= w5;
  /* #205: (@23[1] += @39) */
  for (rr=w23+1, ss=(&w39); rr!=w23+2; rr+=1) *rr += *ss++;
  /* #206: @39 = 142.857 */
  w39 = 1.4285714285714286e+02;
  /* #207: @39 = (@39*@4) */
  w39 *= w4;
  /* #208: (@23[0] += @39) */
  for (rr=w23+0, ss=(&w39); rr!=w23+1; rr+=1) *rr += *ss++;
  /* #209: @52 = (-@23) */
  for (i=0, rr=w52, cs=w23; i<3; ++i) *rr++ = (- *cs++ );
  /* #210: @22 = mac(@21,@52,@22) */
  for (i=0, rr=w22; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w21+j, tt=w52+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #211: {@39, @4, @5} = vertsplit(@22) */
  w39 = w22[0];
  w4 = w22[1];
  w5 = w22[2];
  /* #212: @5 = (@49*@5) */
  w5  = (w49*w5);
  /* #213: (@20[2] += @5) */
  for (rr=w20+2, ss=(&w5); rr!=w20+3; rr+=1) *rr += *ss++;
  /* #214: @5 = 0.007 */
  w5 = 7.0000000000000001e-03;
  /* #215: @4 = (@5*@4) */
  w4  = (w5*w4);
  /* #216: (@20[1] += @4) */
  for (rr=w20+1, ss=(&w4); rr!=w20+2; rr+=1) *rr += *ss++;
  /* #217: @4 = 0.007 */
  w4 = 7.0000000000000001e-03;
  /* #218: @39 = (@4*@39) */
  w39  = (w4*w39);
  /* #219: (@20[0] += @39) */
  for (rr=w20+0, ss=(&w39); rr!=w20+1; rr+=1) *rr += *ss++;
  /* #220: @21 = zeros(3x3) */
  casadi_clear(w21, 9);
  /* #221: @39 = @1[0] */
  for (rr=(&w39), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #222: @4 = (@4*@39) */
  w4 *= w39;
  /* #223: @39 = @1[1] */
  for (rr=(&w39), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #224: @5 = (@5*@39) */
  w5 *= w39;
  /* #225: @39 = @1[2] */
  for (rr=(&w39), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #226: @49 = (@49*@39) */
  w49 *= w39;
  /* #227: @1 = vertcat(@4, @5, @49) */
  rr=w1;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w49;
  /* #228: @1 = @1' */
  /* #229: @21 = mac(@52,@1,@21) */
  for (i=0, rr=w21; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w52+j, tt=w1+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #230: @17 = @21' */
  for (i=0, rr=w17, cs=w21; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #231: {@52, @1, @22} = horzsplit(@17) */
  casadi_copy(w17, 3, w52);
  casadi_copy(w17+3, 3, w1);
  casadi_copy(w17+6, 3, w22);
  /* #232: @22 = @22' */
  /* #233: {@4, @5, NULL} = horzsplit(@22) */
  w4 = w22[0];
  w5 = w22[1];
  /* #234: (@20[0] += @5) */
  for (rr=w20+0, ss=(&w5); rr!=w20+1; rr+=1) *rr += *ss++;
  /* #235: @4 = (-@4) */
  w4 = (- w4 );
  /* #236: (@20[1] += @4) */
  for (rr=w20+1, ss=(&w4); rr!=w20+2; rr+=1) *rr += *ss++;
  /* #237: @1 = @1' */
  /* #238: {@4, NULL, @5} = horzsplit(@1) */
  w4 = w1[0];
  w5 = w1[2];
  /* #239: @5 = (-@5) */
  w5 = (- w5 );
  /* #240: (@20[0] += @5) */
  for (rr=w20+0, ss=(&w5); rr!=w20+1; rr+=1) *rr += *ss++;
  /* #241: (@20[2] += @4) */
  for (rr=w20+2, ss=(&w4); rr!=w20+3; rr+=1) *rr += *ss++;
  /* #242: @52 = @52' */
  /* #243: {NULL, @4, @5} = horzsplit(@52) */
  w4 = w52[1];
  w5 = w52[2];
  /* #244: (@20[1] += @5) */
  for (rr=w20+1, ss=(&w5); rr!=w20+2; rr+=1) *rr += *ss++;
  /* #245: @4 = (-@4) */
  w4 = (- w4 );
  /* #246: (@20[2] += @4) */
  for (rr=w20+2, ss=(&w4); rr!=w20+3; rr+=1) *rr += *ss++;
  /* #247: @16 = zeros(4x4) */
  casadi_clear(w16, 16);
  /* #248: @12 = @12' */
  /* #249: @16 = mac(@3,@12,@16) */
  for (i=0, rr=w16; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w3+j, tt=w12+i*1; k<1; ++k) *rr += ss[k*4]**tt++;
  /* #250: @54 = @16' */
  for (i=0, rr=w54, cs=w16; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #251: {@3, @12, @7, @13} = horzsplit(@54) */
  casadi_copy(w54, 4, w3);
  casadi_copy(w54+4, 4, w12);
  casadi_copy(w54+8, 4, w7);
  casadi_copy(w54+12, 4, w13);
  /* #252: @13 = @13' */
  /* #253: {@4, @5, @49, NULL} = horzsplit(@13) */
  w4 = w13[0];
  w5 = w13[1];
  w49 = w13[2];
  /* #254: (@20[0] += @49) */
  for (rr=w20+0, ss=(&w49); rr!=w20+1; rr+=1) *rr += *ss++;
  /* #255: @5 = (-@5) */
  w5 = (- w5 );
  /* #256: (@20[1] += @5) */
  for (rr=w20+1, ss=(&w5); rr!=w20+2; rr+=1) *rr += *ss++;
  /* #257: (@20[2] += @4) */
  for (rr=w20+2, ss=(&w4); rr!=w20+3; rr+=1) *rr += *ss++;
  /* #258: @7 = @7' */
  /* #259: {@4, @5, NULL, @49} = horzsplit(@7) */
  w4 = w7[0];
  w5 = w7[1];
  w49 = w7[3];
  /* #260: @49 = (-@49) */
  w49 = (- w49 );
  /* #261: (@20[0] += @49) */
  for (rr=w20+0, ss=(&w49); rr!=w20+1; rr+=1) *rr += *ss++;
  /* #262: (@20[2] += @5) */
  for (rr=w20+2, ss=(&w5); rr!=w20+3; rr+=1) *rr += *ss++;
  /* #263: (@20[1] += @4) */
  for (rr=w20+1, ss=(&w4); rr!=w20+2; rr+=1) *rr += *ss++;
  /* #264: @12 = @12' */
  /* #265: {@4, NULL, @5, @49} = horzsplit(@12) */
  w4 = w12[0];
  w5 = w12[2];
  w49 = w12[3];
  /* #266: (@20[1] += @49) */
  for (rr=w20+1, ss=(&w49); rr!=w20+2; rr+=1) *rr += *ss++;
  /* #267: @5 = (-@5) */
  w5 = (- w5 );
  /* #268: (@20[2] += @5) */
  for (rr=w20+2, ss=(&w5); rr!=w20+3; rr+=1) *rr += *ss++;
  /* #269: (@20[0] += @4) */
  for (rr=w20+0, ss=(&w4); rr!=w20+1; rr+=1) *rr += *ss++;
  /* #270: @3 = @3' */
  /* #271: {NULL, @4, @5, NULL} = horzsplit(@3) */
  w4 = w3[1];
  w5 = w3[2];
  /* #272: @5 = (-@5) */
  w5 = (- w5 );
  /* #273: (@20[2] += @5) */
  for (rr=w20+2, ss=(&w5); rr!=w20+3; rr+=1) *rr += *ss++;
  /* #274: @4 = (-@4) */
  w4 = (- w4 );
  /* #275: (@20[0] += @4) */
  for (rr=w20+0, ss=(&w4); rr!=w20+1; rr+=1) *rr += *ss++;
  /* #276: output[0][2] = @20 */
  if (res[0]) casadi_copy(w20, 3, res[0]+7);
  /* #277: {@4, @5, @49} = vertsplit(@23) */
  w4 = w23[0];
  w5 = w23[1];
  w49 = w23[2];
  /* #278: @39 = 0.2 */
  w39 = 2.0000000000000001e-01;
  /* #279: @39 = (@39*@5) */
  w39 *= w5;
  /* #280: @5 = (@49-@39) */
  w5  = (w49-w39);
  /* #281: @6 = 1.47059 */
  w6 = 1.4705882352941175e+00;
  /* #282: @23 = zeros(3x1) */
  casadi_clear(w23, 3);
  /* #283: @50 = 1 */
  w50 = 1.;
  /* #284: @48 = sq(@48) */
  w48 = casadi_sq( w48 );
  /* #285: @40 = sq(@40) */
  w40 = casadi_sq( w40 );
  /* #286: @48 = (@48+@40) */
  w48 += w40;
  /* #287: @48 = (2.*@48) */
  w48 = (2.* w48 );
  /* #288: @50 = (@50-@48) */
  w50 -= w48;
  /* #289: @46 = (@46*@47) */
  w46 *= w47;
  /* #290: @41 = (@41*@45) */
  w41 *= w45;
  /* #291: @46 = (@46-@41) */
  w46 -= w41;
  /* #292: @46 = (2.*@46) */
  w46 = (2.* w46 );
  /* #293: @43 = (@43*@44) */
  w43 *= w44;
  /* #294: @29 = (@29*@42) */
  w29 *= w42;
  /* #295: @43 = (@43+@29) */
  w43 += w29;
  /* #296: @43 = (2.*@43) */
  w43 = (2.* w43 );
  /* #297: @20 = horzcat(@50, @46, @43) */
  rr=w20;
  *rr++ = w50;
  *rr++ = w46;
  *rr++ = w43;
  /* #298: @20 = @20' */
  /* #299: @37 = (@37*@38) */
  w37 *= w38;
  /* #300: @36 = (@36*@30) */
  w36 *= w30;
  /* #301: @37 = (@37+@36) */
  w37 += w36;
  /* #302: @37 = (2.*@37) */
  w37 = (2.* w37 );
  /* #303: @36 = 1 */
  w36 = 1.;
  /* #304: @35 = sq(@35) */
  w35 = casadi_sq( w35 );
  /* #305: @31 = sq(@31) */
  w31 = casadi_sq( w31 );
  /* #306: @35 = (@35+@31) */
  w35 += w31;
  /* #307: @35 = (2.*@35) */
  w35 = (2.* w35 );
  /* #308: @36 = (@36-@35) */
  w36 -= w35;
  /* #309: @33 = (@33*@34) */
  w33 *= w34;
  /* #310: @10 = (@10*@32) */
  w10 *= w32;
  /* #311: @33 = (@33-@10) */
  w33 -= w10;
  /* #312: @33 = (2.*@33) */
  w33 = (2.* w33 );
  /* #313: @52 = horzcat(@37, @36, @33) */
  rr=w52;
  *rr++ = w37;
  *rr++ = w36;
  *rr++ = w33;
  /* #314: @52 = @52' */
  /* #315: @27 = (@27*@28) */
  w27 *= w28;
  /* #316: @11 = (@11*@26) */
  w11 *= w26;
  /* #317: @27 = (@27-@11) */
  w27 -= w11;
  /* #318: @27 = (2.*@27) */
  w27 = (2.* w27 );
  /* #319: @24 = (@24*@25) */
  w24 *= w25;
  /* #320: @19 = (@19*@18) */
  w19 *= w18;
  /* #321: @24 = (@24+@19) */
  w24 += w19;
  /* #322: @24 = (2.*@24) */
  w24 = (2.* w24 );
  /* #323: @19 = 1 */
  w19 = 1.;
  /* #324: @9 = sq(@9) */
  w9 = casadi_sq( w9 );
  /* #325: @8 = sq(@8) */
  w8 = casadi_sq( w8 );
  /* #326: @9 = (@9+@8) */
  w9 += w8;
  /* #327: @9 = (2.*@9) */
  w9 = (2.* w9 );
  /* #328: @19 = (@19-@9) */
  w19 -= w9;
  /* #329: @1 = horzcat(@27, @24, @19) */
  rr=w1;
  *rr++ = w27;
  *rr++ = w24;
  *rr++ = w19;
  /* #330: @1 = @1' */
  /* #331: @17 = horzcat(@20, @52, @1) */
  rr=w17;
  for (i=0, cs=w20; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w52; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w1; i<3; ++i) *rr++ = *cs++;
  /* #332: @23 = mac(@17,@2,@23) */
  for (i=0, rr=w23; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w2+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #333: @23 = (@6*@23) */
  for (i=0, rr=w23, cs=w23; i<3; ++i) (*rr++)  = (w6*(*cs++));
  /* #334: {NULL, NULL, @6} = vertsplit(@23) */
  w6 = w23[2];
  /* #335: @5 = (@5+@6) */
  w5 += w6;
  /* #336: output[0][3] = @5 */
  if (res[0]) res[0][10] = w5;
  /* #337: @5 = 0.2 */
  w5 = 2.0000000000000001e-01;
  /* #338: @5 = (@5*@4) */
  w5 *= w4;
  /* #339: @4 = (@5-@49) */
  w4  = (w5-w49);
  /* #340: @4 = (@4+@6) */
  w4 += w6;
  /* #341: output[0][4] = @4 */
  if (res[0]) res[0][11] = w4;
  /* #342: @39 = (@49+@39) */
  w39  = (w49+w39);
  /* #343: @39 = (@39+@6) */
  w39 += w6;
  /* #344: output[0][5] = @39 */
  if (res[0]) res[0][12] = w39;
  /* #345: @5 = (-@5) */
  w5 = (- w5 );
  /* #346: @5 = (@5-@49) */
  w5 -= w49;
  /* #347: @5 = (@5+@6) */
  w5 += w6;
  /* #348: output[0][6] = @5 */
  if (res[0]) res[0][13] = w5;
  return 0;
}

CASADI_SYMBOL_EXPORT int Quadrotor_model_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Quadrotor_model_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Quadrotor_model_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Quadrotor_model_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Quadrotor_model_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Quadrotor_model_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Quadrotor_model_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void Quadrotor_model_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Quadrotor_model_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Quadrotor_model_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Quadrotor_model_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Quadrotor_model_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Quadrotor_model_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Quadrotor_model_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Quadrotor_model_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Quadrotor_model_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 7;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 149;
  return 0;
}

CASADI_SYMBOL_EXPORT int Quadrotor_model_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 7*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 149*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
