/* This file was automatically generated by CasADi 3.6.5.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Quadrotor_model_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {0, 0, 0};

static const casadi_real casadi_c0[3] = {0., 0., -9.8100000000000005e+00};

/* Quadrotor_model_expl_ode_fun:(i0[13],i1[4],i2[])->(o0[13]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real *w0=w+4, *w1=w+7, w2, *w3=w+11, w4, w5, w6, w7, *w8=w+19, *w9=w+22, *w10=w+25, *w11=w+28, *w12=w+37, w13, w14, *w15=w+48, w16, w17, *w18=w+54, *w19=w+58, *w20=w+62, *w21=w+66, *w22=w+70, *w23=w+86, *w24=w+102;
  /* #0: @0 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 3, w0);
  /* #1: output[0][0] = @0 */
  casadi_copy(w0, 3, res[0]);
  /* #2: @0 = [0, 0, -9.81] */
  casadi_copy(casadi_c0, 3, w0);
  /* #3: @1 = zeros(3x1) */
  casadi_clear(w1, 3);
  /* #4: @2 = 1 */
  w2 = 1.;
  /* #5: @3 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+6 : 0, 4, w3);
  /* #6: @4 = @3[1] */
  for (rr=(&w4), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #7: @4 = sq(@4) */
  w4 = casadi_sq( w4 );
  /* #8: @5 = @3[2] */
  for (rr=(&w5), ss=w3+2; ss!=w3+3; ss+=1) *rr++ = *ss;
  /* #9: @5 = sq(@5) */
  w5 = casadi_sq( w5 );
  /* #10: @4 = (@4+@5) */
  w4 += w5;
  /* #11: @4 = (2.*@4) */
  w4 = (2.* w4 );
  /* #12: @2 = (@2-@4) */
  w2 -= w4;
  /* #13: @4 = @3[0] */
  for (rr=(&w4), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #14: @5 = @3[1] */
  for (rr=(&w5), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #15: @4 = (@4*@5) */
  w4 *= w5;
  /* #16: @5 = @3[3] */
  for (rr=(&w5), ss=w3+3; ss!=w3+4; ss+=1) *rr++ = *ss;
  /* #17: @6 = @3[2] */
  for (rr=(&w6), ss=w3+2; ss!=w3+3; ss+=1) *rr++ = *ss;
  /* #18: @5 = (@5*@6) */
  w5 *= w6;
  /* #19: @4 = (@4-@5) */
  w4 -= w5;
  /* #20: @4 = (2.*@4) */
  w4 = (2.* w4 );
  /* #21: @5 = @3[0] */
  for (rr=(&w5), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #22: @6 = @3[2] */
  for (rr=(&w6), ss=w3+2; ss!=w3+3; ss+=1) *rr++ = *ss;
  /* #23: @5 = (@5*@6) */
  w5 *= w6;
  /* #24: @6 = @3[3] */
  for (rr=(&w6), ss=w3+3; ss!=w3+4; ss+=1) *rr++ = *ss;
  /* #25: @7 = @3[1] */
  for (rr=(&w7), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #26: @6 = (@6*@7) */
  w6 *= w7;
  /* #27: @5 = (@5+@6) */
  w5 += w6;
  /* #28: @5 = (2.*@5) */
  w5 = (2.* w5 );
  /* #29: @8 = horzcat(@2, @4, @5) */
  rr=w8;
  *rr++ = w2;
  *rr++ = w4;
  *rr++ = w5;
  /* #30: @8 = @8' */
  /* #31: @2 = @3[0] */
  for (rr=(&w2), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #32: @4 = @3[1] */
  for (rr=(&w4), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #33: @2 = (@2*@4) */
  w2 *= w4;
  /* #34: @4 = @3[3] */
  for (rr=(&w4), ss=w3+3; ss!=w3+4; ss+=1) *rr++ = *ss;
  /* #35: @5 = @3[2] */
  for (rr=(&w5), ss=w3+2; ss!=w3+3; ss+=1) *rr++ = *ss;
  /* #36: @4 = (@4*@5) */
  w4 *= w5;
  /* #37: @2 = (@2+@4) */
  w2 += w4;
  /* #38: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #39: @4 = 1 */
  w4 = 1.;
  /* #40: @5 = @3[0] */
  for (rr=(&w5), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #41: @5 = sq(@5) */
  w5 = casadi_sq( w5 );
  /* #42: @6 = @3[2] */
  for (rr=(&w6), ss=w3+2; ss!=w3+3; ss+=1) *rr++ = *ss;
  /* #43: @6 = sq(@6) */
  w6 = casadi_sq( w6 );
  /* #44: @5 = (@5+@6) */
  w5 += w6;
  /* #45: @5 = (2.*@5) */
  w5 = (2.* w5 );
  /* #46: @4 = (@4-@5) */
  w4 -= w5;
  /* #47: @5 = @3[1] */
  for (rr=(&w5), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #48: @6 = @3[2] */
  for (rr=(&w6), ss=w3+2; ss!=w3+3; ss+=1) *rr++ = *ss;
  /* #49: @5 = (@5*@6) */
  w5 *= w6;
  /* #50: @6 = @3[3] */
  for (rr=(&w6), ss=w3+3; ss!=w3+4; ss+=1) *rr++ = *ss;
  /* #51: @7 = @3[0] */
  for (rr=(&w7), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #52: @6 = (@6*@7) */
  w6 *= w7;
  /* #53: @5 = (@5-@6) */
  w5 -= w6;
  /* #54: @5 = (2.*@5) */
  w5 = (2.* w5 );
  /* #55: @9 = horzcat(@2, @4, @5) */
  rr=w9;
  *rr++ = w2;
  *rr++ = w4;
  *rr++ = w5;
  /* #56: @9 = @9' */
  /* #57: @2 = @3[0] */
  for (rr=(&w2), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #58: @4 = @3[2] */
  for (rr=(&w4), ss=w3+2; ss!=w3+3; ss+=1) *rr++ = *ss;
  /* #59: @2 = (@2*@4) */
  w2 *= w4;
  /* #60: @4 = @3[3] */
  for (rr=(&w4), ss=w3+3; ss!=w3+4; ss+=1) *rr++ = *ss;
  /* #61: @5 = @3[1] */
  for (rr=(&w5), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #62: @4 = (@4*@5) */
  w4 *= w5;
  /* #63: @2 = (@2-@4) */
  w2 -= w4;
  /* #64: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #65: @4 = @3[1] */
  for (rr=(&w4), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #66: @5 = @3[2] */
  for (rr=(&w5), ss=w3+2; ss!=w3+3; ss+=1) *rr++ = *ss;
  /* #67: @4 = (@4*@5) */
  w4 *= w5;
  /* #68: @5 = @3[3] */
  for (rr=(&w5), ss=w3+3; ss!=w3+4; ss+=1) *rr++ = *ss;
  /* #69: @6 = @3[0] */
  for (rr=(&w6), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #70: @5 = (@5*@6) */
  w5 *= w6;
  /* #71: @4 = (@4+@5) */
  w4 += w5;
  /* #72: @4 = (2.*@4) */
  w4 = (2.* w4 );
  /* #73: @5 = 1 */
  w5 = 1.;
  /* #74: @6 = @3[0] */
  for (rr=(&w6), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #75: @6 = sq(@6) */
  w6 = casadi_sq( w6 );
  /* #76: @7 = @3[1] */
  for (rr=(&w7), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #77: @7 = sq(@7) */
  w7 = casadi_sq( w7 );
  /* #78: @6 = (@6+@7) */
  w6 += w7;
  /* #79: @6 = (2.*@6) */
  w6 = (2.* w6 );
  /* #80: @5 = (@5-@6) */
  w5 -= w6;
  /* #81: @10 = horzcat(@2, @4, @5) */
  rr=w10;
  *rr++ = w2;
  *rr++ = w4;
  *rr++ = w5;
  /* #82: @10 = @10' */
  /* #83: @11 = horzcat(@8, @9, @10) */
  rr=w11;
  for (i=0, cs=w8; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w9; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w10; i<3; ++i) *rr++ = *cs++;
  /* #84: @12 = @11' */
  for (i=0, rr=w12, cs=w11; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #85: @2 = 0 */
  w2 = 0.;
  /* #86: @4 = 0 */
  w4 = 0.;
  /* #87: @5 = input[1][0] */
  w5 = arg[1] ? arg[1][0] : 0;
  /* #88: @6 = input[1][1] */
  w6 = arg[1] ? arg[1][1] : 0;
  /* #89: @7 = (@5+@6) */
  w7  = (w5+w6);
  /* #90: @13 = input[1][2] */
  w13 = arg[1] ? arg[1][2] : 0;
  /* #91: @7 = (@7+@13) */
  w7 += w13;
  /* #92: @14 = input[1][3] */
  w14 = arg[1] ? arg[1][3] : 0;
  /* #93: @7 = (@7+@14) */
  w7 += w14;
  /* #94: @8 = vertcat(@2, @4, @7) */
  rr=w8;
  *rr++ = w2;
  *rr++ = w4;
  *rr++ = w7;
  /* #95: @2 = 0.68 */
  w2 = 6.8000000000000005e-01;
  /* #96: @8 = (@8/@2) */
  for (i=0, rr=w8; i<3; ++i) (*rr++) /= w2;
  /* #97: @1 = mac(@12,@8,@1) */
  for (i=0, rr=w1; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w12+j, tt=w8+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #98: @0 = (@0+@1) */
  for (i=0, rr=w0, cs=w1; i<3; ++i) (*rr++) += (*cs++);
  /* #99: output[0][1] = @0 */
  if (res[0]) casadi_copy(w0, 3, res[0]+3);
  /* #100: @2 = 0.5 */
  w2 = 5.0000000000000000e-01;
  /* #101: @15 = zeros(4x1) */
  casadi_clear(w15, 4);
  /* #102: @0 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+10 : 0, 3, w0);
  /* #103: @4 = @0[2] */
  for (rr=(&w4), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #104: @7 = 0 */
  w7 = 0.;
  /* #105: @16 = @0[1] */
  for (rr=(&w16), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #106: @16 = (-@16) */
  w16 = (- w16 );
  /* #107: @17 = @0[2] */
  for (rr=(&w17), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #108: @17 = (-@17) */
  w17 = (- w17 );
  /* #109: @18 = horzcat(@4, @7, @16, @17) */
  rr=w18;
  *rr++ = w4;
  *rr++ = w7;
  *rr++ = w16;
  *rr++ = w17;
  /* #110: @18 = @18' */
  /* #111: @4 = 0 */
  w4 = 0.;
  /* #112: @7 = @0[2] */
  for (rr=(&w7), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #113: @16 = @0[1] */
  for (rr=(&w16), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #114: @16 = (-@16) */
  w16 = (- w16 );
  /* #115: @17 = @0[0] */
  for (rr=(&w17), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #116: @19 = horzcat(@4, @7, @16, @17) */
  rr=w19;
  *rr++ = w4;
  *rr++ = w7;
  *rr++ = w16;
  *rr++ = w17;
  /* #117: @19 = @19' */
  /* #118: @4 = @0[0] */
  for (rr=(&w4), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #119: @7 = @0[1] */
  for (rr=(&w7), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #120: @16 = @0[2] */
  for (rr=(&w16), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #121: @17 = 0 */
  w17 = 0.;
  /* #122: @20 = horzcat(@4, @7, @16, @17) */
  rr=w20;
  *rr++ = w4;
  *rr++ = w7;
  *rr++ = w16;
  *rr++ = w17;
  /* #123: @20 = @20' */
  /* #124: @4 = @0[1] */
  for (rr=(&w4), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #125: @7 = @0[0] */
  for (rr=(&w7), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #126: @7 = (-@7) */
  w7 = (- w7 );
  /* #127: @16 = 0 */
  w16 = 0.;
  /* #128: @17 = @0[2] */
  for (rr=(&w17), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #129: @21 = horzcat(@4, @7, @16, @17) */
  rr=w21;
  *rr++ = w4;
  *rr++ = w7;
  *rr++ = w16;
  *rr++ = w17;
  /* #130: @21 = @21' */
  /* #131: @22 = horzcat(@18, @19, @20, @21) */
  rr=w22;
  for (i=0, cs=w18; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<4; ++i) *rr++ = *cs++;
  /* #132: @23 = @22' */
  for (i=0, rr=w23, cs=w22; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #133: @15 = mac(@23,@3,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w23+j, tt=w3+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #134: @15 = (@2*@15) */
  for (i=0, rr=w15, cs=w15; i<4; ++i) (*rr++)  = (w2*(*cs++));
  /* #135: output[0][2] = @15 */
  if (res[0]) casadi_copy(w15, 4, res[0]+6);
  /* #136: @2 = 142.857 */
  w2 = 1.4285714285714286e+02;
  /* #137: @4 = 0.2 */
  w4 = 2.0000000000000001e-01;
  /* #138: @7 = (@6-@14) */
  w7  = (w6-w14);
  /* #139: @4 = (@4*@7) */
  w4 *= w7;
  /* #140: @7 = 0.2 */
  w7 = 2.0000000000000001e-01;
  /* #141: @16 = (@13-@5) */
  w16  = (w13-w5);
  /* #142: @7 = (@7*@16) */
  w7 *= w16;
  /* #143: @5 = (@5-@6) */
  w5 -= w6;
  /* #144: @5 = (@5+@13) */
  w5 += w13;
  /* #145: @5 = (@5-@14) */
  w5 -= w14;
  /* #146: @1 = vertcat(@4, @7, @5) */
  rr=w1;
  *rr++ = w4;
  *rr++ = w7;
  *rr++ = w5;
  /* #147: @8 = zeros(3x1) */
  casadi_clear(w8, 3);
  /* #148: @4 = 0 */
  w4 = 0.;
  /* #149: @7 = @0[2] */
  for (rr=(&w7), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #150: @7 = (-@7) */
  w7 = (- w7 );
  /* #151: @5 = @0[1] */
  for (rr=(&w5), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #152: @9 = horzcat(@4, @7, @5) */
  rr=w9;
  *rr++ = w4;
  *rr++ = w7;
  *rr++ = w5;
  /* #153: @9 = @9' */
  /* #154: @4 = @0[2] */
  for (rr=(&w4), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #155: @7 = 0 */
  w7 = 0.;
  /* #156: @5 = @0[0] */
  for (rr=(&w5), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #157: @5 = (-@5) */
  w5 = (- w5 );
  /* #158: @10 = horzcat(@4, @7, @5) */
  rr=w10;
  *rr++ = w4;
  *rr++ = w7;
  *rr++ = w5;
  /* #159: @10 = @10' */
  /* #160: @4 = @0[1] */
  for (rr=(&w4), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #161: @4 = (-@4) */
  w4 = (- w4 );
  /* #162: @7 = @0[0] */
  for (rr=(&w7), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #163: @5 = 0 */
  w5 = 0.;
  /* #164: @24 = horzcat(@4, @7, @5) */
  rr=w24;
  *rr++ = w4;
  *rr++ = w7;
  *rr++ = w5;
  /* #165: @24 = @24' */
  /* #166: @12 = horzcat(@9, @10, @24) */
  rr=w12;
  for (i=0, cs=w9; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w10; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w24; i<3; ++i) *rr++ = *cs++;
  /* #167: @11 = @12' */
  for (i=0, rr=w11, cs=w12; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #168: @4 = 0.007 */
  w4 = 7.0000000000000001e-03;
  /* #169: @7 = @0[0] */
  for (rr=(&w7), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #170: @4 = (@4*@7) */
  w4 *= w7;
  /* #171: @7 = 0.007 */
  w7 = 7.0000000000000001e-03;
  /* #172: @5 = @0[1] */
  for (rr=(&w5), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #173: @7 = (@7*@5) */
  w7 *= w5;
  /* #174: @5 = 0.012 */
  w5 = 1.2000000000000000e-02;
  /* #175: @14 = @0[2] */
  for (rr=(&w14), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #176: @5 = (@5*@14) */
  w5 *= w14;
  /* #177: @0 = vertcat(@4, @7, @5) */
  rr=w0;
  *rr++ = w4;
  *rr++ = w7;
  *rr++ = w5;
  /* #178: @8 = mac(@11,@0,@8) */
  for (i=0, rr=w8; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w11+j, tt=w0+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #179: @1 = (@1-@8) */
  for (i=0, rr=w1, cs=w8; i<3; ++i) (*rr++) -= (*cs++);
  /* #180: @4 = @1[0] */
  for (rr=(&w4), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #181: @2 = (@2*@4) */
  w2 *= w4;
  /* #182: output[0][3] = @2 */
  if (res[0]) res[0][10] = w2;
  /* #183: @2 = 142.857 */
  w2 = 1.4285714285714286e+02;
  /* #184: @4 = @1[1] */
  for (rr=(&w4), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #185: @2 = (@2*@4) */
  w2 *= w4;
  /* #186: output[0][4] = @2 */
  if (res[0]) res[0][11] = w2;
  /* #187: @2 = 83.3333 */
  w2 = 8.3333333333333329e+01;
  /* #188: @4 = @1[2] */
  for (rr=(&w4), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #189: @2 = (@2*@4) */
  w2 *= w4;
  /* #190: output[0][5] = @2 */
  if (res[0]) res[0][12] = w2;
  return 0;
}

CASADI_SYMBOL_EXPORT int Quadrotor_model_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Quadrotor_model_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Quadrotor_model_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Quadrotor_model_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Quadrotor_model_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Quadrotor_model_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Quadrotor_model_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void Quadrotor_model_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Quadrotor_model_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int Quadrotor_model_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Quadrotor_model_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Quadrotor_model_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Quadrotor_model_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Quadrotor_model_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Quadrotor_model_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Quadrotor_model_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 105;
  return 0;
}

CASADI_SYMBOL_EXPORT int Quadrotor_model_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 105*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
