/* This file was automatically generated by CasADi 3.6.5.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Quadrotor_model_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {0, 0, 0};

static const casadi_real casadi_c0[3] = {0., 0., -9.8100000000000005e+00};

/* Quadrotor_model_expl_ode_fun:(i0[13],i1[4],i2[])->(o0[13]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real *w0=w+4, *w1=w+7, w2, *w3=w+11, w4, w5, w6, w7, w8, w9, w10, *w11=w+22, *w12=w+25, *w13=w+28, *w14=w+31, *w15=w+40, *w16=w+49, w17, w18, w19, *w20=w+56, *w21=w+60, *w22=w+64, *w23=w+68, *w24=w+72, *w25=w+88, *w26=w+104;
  /* #0: @0 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 3, w0);
  /* #1: output[0][0] = @0 */
  casadi_copy(w0, 3, res[0]);
  /* #2: @0 = [0, 0, -9.81] */
  casadi_copy(casadi_c0, 3, w0);
  /* #3: @1 = zeros(3x1) */
  casadi_clear(w1, 3);
  /* #4: @2 = 1 */
  w2 = 1.;
  /* #5: @3 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+6 : 0, 4, w3);
  /* #6: @4 = @3[1] */
  for (rr=(&w4), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #7: @5 = sq(@4) */
  w5 = casadi_sq( w4 );
  /* #8: @6 = @3[2] */
  for (rr=(&w6), ss=w3+2; ss!=w3+3; ss+=1) *rr++ = *ss;
  /* #9: @7 = sq(@6) */
  w7 = casadi_sq( w6 );
  /* #10: @5 = (@5+@7) */
  w5 += w7;
  /* #11: @5 = (2.*@5) */
  w5 = (2.* w5 );
  /* #12: @2 = (@2-@5) */
  w2 -= w5;
  /* #13: @5 = @3[0] */
  for (rr=(&w5), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #14: @7 = (@5*@4) */
  w7  = (w5*w4);
  /* #15: @8 = @3[3] */
  for (rr=(&w8), ss=w3+3; ss!=w3+4; ss+=1) *rr++ = *ss;
  /* #16: @9 = (@8*@6) */
  w9  = (w8*w6);
  /* #17: @7 = (@7-@9) */
  w7 -= w9;
  /* #18: @7 = (2.*@7) */
  w7 = (2.* w7 );
  /* #19: @9 = (@5*@6) */
  w9  = (w5*w6);
  /* #20: @10 = (@8*@4) */
  w10  = (w8*w4);
  /* #21: @9 = (@9+@10) */
  w9 += w10;
  /* #22: @9 = (2.*@9) */
  w9 = (2.* w9 );
  /* #23: @11 = horzcat(@2, @7, @9) */
  rr=w11;
  *rr++ = w2;
  *rr++ = w7;
  *rr++ = w9;
  /* #24: @11 = @11' */
  /* #25: @2 = (@4*@5) */
  w2  = (w4*w5);
  /* #26: @7 = (@8*@6) */
  w7  = (w8*w6);
  /* #27: @2 = (@2+@7) */
  w2 += w7;
  /* #28: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #29: @7 = 1 */
  w7 = 1.;
  /* #30: @9 = sq(@5) */
  w9 = casadi_sq( w5 );
  /* #31: @10 = sq(@6) */
  w10 = casadi_sq( w6 );
  /* #32: @9 = (@9+@10) */
  w9 += w10;
  /* #33: @9 = (2.*@9) */
  w9 = (2.* w9 );
  /* #34: @7 = (@7-@9) */
  w7 -= w9;
  /* #35: @9 = (@4*@6) */
  w9  = (w4*w6);
  /* #36: @10 = (@8*@5) */
  w10  = (w8*w5);
  /* #37: @9 = (@9-@10) */
  w9 -= w10;
  /* #38: @9 = (2.*@9) */
  w9 = (2.* w9 );
  /* #39: @12 = horzcat(@2, @7, @9) */
  rr=w12;
  *rr++ = w2;
  *rr++ = w7;
  *rr++ = w9;
  /* #40: @12 = @12' */
  /* #41: @2 = (@6*@5) */
  w2  = (w6*w5);
  /* #42: @7 = (@8*@4) */
  w7  = (w8*w4);
  /* #43: @2 = (@2-@7) */
  w2 -= w7;
  /* #44: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #45: @6 = (@6*@4) */
  w6 *= w4;
  /* #46: @8 = (@8*@5) */
  w8 *= w5;
  /* #47: @6 = (@6+@8) */
  w6 += w8;
  /* #48: @6 = (2.*@6) */
  w6 = (2.* w6 );
  /* #49: @8 = 1 */
  w8 = 1.;
  /* #50: @5 = sq(@5) */
  w5 = casadi_sq( w5 );
  /* #51: @4 = sq(@4) */
  w4 = casadi_sq( w4 );
  /* #52: @5 = (@5+@4) */
  w5 += w4;
  /* #53: @5 = (2.*@5) */
  w5 = (2.* w5 );
  /* #54: @8 = (@8-@5) */
  w8 -= w5;
  /* #55: @13 = horzcat(@2, @6, @8) */
  rr=w13;
  *rr++ = w2;
  *rr++ = w6;
  *rr++ = w8;
  /* #56: @13 = @13' */
  /* #57: @14 = horzcat(@11, @12, @13) */
  rr=w14;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  /* #58: @15 = @14' */
  for (i=0, rr=w15, cs=w14; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #59: @2 = 0 */
  w2 = 0.;
  /* #60: @6 = 0 */
  w6 = 0.;
  /* #61: @8 = input[1][0] */
  w8 = arg[1] ? arg[1][0] : 0;
  /* #62: @5 = input[1][1] */
  w5 = arg[1] ? arg[1][1] : 0;
  /* #63: @4 = (@8+@5) */
  w4  = (w8+w5);
  /* #64: @7 = input[1][2] */
  w7 = arg[1] ? arg[1][2] : 0;
  /* #65: @4 = (@4+@7) */
  w4 += w7;
  /* #66: @9 = input[1][3] */
  w9 = arg[1] ? arg[1][3] : 0;
  /* #67: @4 = (@4+@9) */
  w4 += w9;
  /* #68: @11 = vertcat(@2, @6, @4) */
  rr=w11;
  *rr++ = w2;
  *rr++ = w6;
  *rr++ = w4;
  /* #69: @2 = 0.68 */
  w2 = 6.8000000000000005e-01;
  /* #70: @11 = (@11/@2) */
  for (i=0, rr=w11; i<3; ++i) (*rr++) /= w2;
  /* #71: @1 = mac(@15,@11,@1) */
  for (i=0, rr=w1; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w15+j, tt=w11+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #72: @0 = (@0+@1) */
  for (i=0, rr=w0, cs=w1; i<3; ++i) (*rr++) += (*cs++);
  /* #73: output[0][1] = @0 */
  if (res[0]) casadi_copy(w0, 3, res[0]+3);
  /* #74: @2 = 0.5 */
  w2 = 5.0000000000000000e-01;
  /* #75: @16 = zeros(4x1) */
  casadi_clear(w16, 4);
  /* #76: @0 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+10 : 0, 3, w0);
  /* #77: @6 = @0[2] */
  for (rr=(&w6), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #78: @4 = 0 */
  w4 = 0.;
  /* #79: @10 = @0[0] */
  for (rr=(&w10), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #80: @17 = (-@10) */
  w17 = (- w10 );
  /* #81: @18 = @0[1] */
  for (rr=(&w18), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #82: @19 = (-@18) */
  w19 = (- w18 );
  /* #83: @20 = horzcat(@6, @4, @17, @19) */
  rr=w20;
  *rr++ = w6;
  *rr++ = w4;
  *rr++ = w17;
  *rr++ = w19;
  /* #84: @20 = @20' */
  /* #85: @4 = 0 */
  w4 = 0.;
  /* #86: @17 = (-@18) */
  w17 = (- w18 );
  /* #87: @21 = horzcat(@4, @6, @17, @10) */
  rr=w21;
  *rr++ = w4;
  *rr++ = w6;
  *rr++ = w17;
  *rr++ = w10;
  /* #88: @21 = @21' */
  /* #89: @17 = 0 */
  w17 = 0.;
  /* #90: @22 = horzcat(@10, @18, @6, @17) */
  rr=w22;
  *rr++ = w10;
  *rr++ = w18;
  *rr++ = w6;
  *rr++ = w17;
  /* #91: @22 = @22' */
  /* #92: @10 = (-@10) */
  w10 = (- w10 );
  /* #93: @23 = horzcat(@18, @10, @4, @6) */
  rr=w23;
  *rr++ = w18;
  *rr++ = w10;
  *rr++ = w4;
  *rr++ = w6;
  /* #94: @23 = @23' */
  /* #95: @24 = horzcat(@20, @21, @22, @23) */
  rr=w24;
  for (i=0, cs=w20; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<4; ++i) *rr++ = *cs++;
  /* #96: @25 = @24' */
  for (i=0, rr=w25, cs=w24; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #97: @16 = mac(@25,@3,@16) */
  for (i=0, rr=w16; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w25+j, tt=w3+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #98: @16 = (@2*@16) */
  for (i=0, rr=w16, cs=w16; i<4; ++i) (*rr++)  = (w2*(*cs++));
  /* #99: output[0][2] = @16 */
  if (res[0]) casadi_copy(w16, 4, res[0]+6);
  /* #100: @2 = 142.857 */
  w2 = 1.4285714285714286e+02;
  /* #101: @18 = 0.17 */
  w18 = 1.7000000000000001e-01;
  /* #102: @10 = (@5-@9) */
  w10  = (w5-w9);
  /* #103: @18 = (@18*@10) */
  w18 *= w10;
  /* #104: @10 = 0.17 */
  w10 = 1.7000000000000001e-01;
  /* #105: @4 = (@7-@8) */
  w4  = (w7-w8);
  /* #106: @10 = (@10*@4) */
  w10 *= w4;
  /* #107: @4 = 0.1 */
  w4 = 1.0000000000000001e-01;
  /* #108: @8 = (@8-@5) */
  w8 -= w5;
  /* #109: @8 = (@8+@7) */
  w8 += w7;
  /* #110: @8 = (@8-@9) */
  w8 -= w9;
  /* #111: @4 = (@4*@8) */
  w4 *= w8;
  /* #112: @1 = vertcat(@18, @10, @4) */
  rr=w1;
  *rr++ = w18;
  *rr++ = w10;
  *rr++ = w4;
  /* #113: @11 = zeros(3x1) */
  casadi_clear(w11, 3);
  /* #114: @18 = 0 */
  w18 = 0.;
  /* #115: @10 = @0[2] */
  for (rr=(&w10), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #116: @10 = (-@10) */
  w10 = (- w10 );
  /* #117: @4 = @0[1] */
  for (rr=(&w4), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #118: @12 = horzcat(@18, @10, @4) */
  rr=w12;
  *rr++ = w18;
  *rr++ = w10;
  *rr++ = w4;
  /* #119: @12 = @12' */
  /* #120: @18 = @0[2] */
  for (rr=(&w18), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #121: @10 = 0 */
  w10 = 0.;
  /* #122: @4 = @0[0] */
  for (rr=(&w4), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #123: @4 = (-@4) */
  w4 = (- w4 );
  /* #124: @13 = horzcat(@18, @10, @4) */
  rr=w13;
  *rr++ = w18;
  *rr++ = w10;
  *rr++ = w4;
  /* #125: @13 = @13' */
  /* #126: @18 = @0[1] */
  for (rr=(&w18), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #127: @18 = (-@18) */
  w18 = (- w18 );
  /* #128: @10 = @0[0] */
  for (rr=(&w10), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #129: @4 = 0 */
  w4 = 0.;
  /* #130: @26 = horzcat(@18, @10, @4) */
  rr=w26;
  *rr++ = w18;
  *rr++ = w10;
  *rr++ = w4;
  /* #131: @26 = @26' */
  /* #132: @15 = horzcat(@12, @13, @26) */
  rr=w15;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w26; i<3; ++i) *rr++ = *cs++;
  /* #133: @14 = @15' */
  for (i=0, rr=w14, cs=w15; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #134: @18 = 0.007 */
  w18 = 7.0000000000000001e-03;
  /* #135: @10 = @0[0] */
  for (rr=(&w10), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #136: @18 = (@18*@10) */
  w18 *= w10;
  /* #137: @10 = 0.007 */
  w10 = 7.0000000000000001e-03;
  /* #138: @4 = @0[1] */
  for (rr=(&w4), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #139: @10 = (@10*@4) */
  w10 *= w4;
  /* #140: @4 = 0.012 */
  w4 = 1.2000000000000000e-02;
  /* #141: @8 = @0[2] */
  for (rr=(&w8), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #142: @4 = (@4*@8) */
  w4 *= w8;
  /* #143: @0 = vertcat(@18, @10, @4) */
  rr=w0;
  *rr++ = w18;
  *rr++ = w10;
  *rr++ = w4;
  /* #144: @11 = mac(@14,@0,@11) */
  for (i=0, rr=w11; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w14+j, tt=w0+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #145: @1 = (@1-@11) */
  for (i=0, rr=w1, cs=w11; i<3; ++i) (*rr++) -= (*cs++);
  /* #146: @18 = @1[0] */
  for (rr=(&w18), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #147: @2 = (@2*@18) */
  w2 *= w18;
  /* #148: output[0][3] = @2 */
  if (res[0]) res[0][10] = w2;
  /* #149: @2 = 142.857 */
  w2 = 1.4285714285714286e+02;
  /* #150: @18 = @1[1] */
  for (rr=(&w18), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #151: @2 = (@2*@18) */
  w2 *= w18;
  /* #152: output[0][4] = @2 */
  if (res[0]) res[0][11] = w2;
  /* #153: @2 = 83.3333 */
  w2 = 8.3333333333333329e+01;
  /* #154: @18 = @1[2] */
  for (rr=(&w18), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #155: @2 = (@2*@18) */
  w2 *= w18;
  /* #156: output[0][5] = @2 */
  if (res[0]) res[0][12] = w2;
  return 0;
}

CASADI_SYMBOL_EXPORT int Quadrotor_model_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Quadrotor_model_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Quadrotor_model_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Quadrotor_model_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Quadrotor_model_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Quadrotor_model_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Quadrotor_model_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void Quadrotor_model_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Quadrotor_model_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int Quadrotor_model_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Quadrotor_model_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Quadrotor_model_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Quadrotor_model_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Quadrotor_model_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Quadrotor_model_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Quadrotor_model_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 107;
  return 0;
}

CASADI_SYMBOL_EXPORT int Quadrotor_model_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 107*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
