/* This file was automatically generated by CasADi 3.6.5.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Quadrotor_model_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[18] = {17, 1, 0, 14, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};

/* Quadrotor_model_expl_vde_adj:(i0[13],i1[13],i2[4],i3[])->(o0[17x1,14nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real *w0=w+4, *w1=w+17, *w2=w+20, *w3=w+23, w4, w5, w6, *w7=w+30, w8, w9, w10, w11, w12, w13, *w14=w+40, *w15=w+44, *w16=w+48, *w17=w+52, *w18=w+56, *w19=w+72, *w20=w+81, *w21=w+84, *w22=w+93, *w23=w+96, w24, w25, w26, w27, w28, w29, w30, w31, w32, *w33=w+108, *w34=w+111, *w35=w+114;
  /* #0: @0 = input[1][0] */
  casadi_copy(arg[1], 13, w0);
  /* #1: {@1, @2, @3, @4, @5, @6} = vertsplit(@0) */
  casadi_copy(w0, 3, w1);
  casadi_copy(w0+3, 3, w2);
  casadi_copy(w0+6, 4, w3);
  w4 = w0[10];
  w5 = w0[11];
  w6 = w0[12];
  /* #2: output[0][0] = @1 */
  casadi_copy(w1, 3, res[0]);
  /* #3: @7 = zeros(4x1) */
  casadi_clear(w7, 4);
  /* #4: @1 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+10 : 0, 3, w1);
  /* #5: @8 = @1[2] */
  for (rr=(&w8), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #6: @9 = 0 */
  w9 = 0.;
  /* #7: @10 = @1[0] */
  for (rr=(&w10), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #8: @11 = (-@10) */
  w11 = (- w10 );
  /* #9: @12 = @1[1] */
  for (rr=(&w12), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #10: @13 = (-@12) */
  w13 = (- w12 );
  /* #11: @14 = horzcat(@8, @9, @11, @13) */
  rr=w14;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w11;
  *rr++ = w13;
  /* #12: @14 = @14' */
  /* #13: @9 = 0 */
  w9 = 0.;
  /* #14: @11 = (-@12) */
  w11 = (- w12 );
  /* #15: @15 = horzcat(@9, @8, @11, @10) */
  rr=w15;
  *rr++ = w9;
  *rr++ = w8;
  *rr++ = w11;
  *rr++ = w10;
  /* #16: @15 = @15' */
  /* #17: @11 = 0 */
  w11 = 0.;
  /* #18: @16 = horzcat(@10, @12, @8, @11) */
  rr=w16;
  *rr++ = w10;
  *rr++ = w12;
  *rr++ = w8;
  *rr++ = w11;
  /* #19: @16 = @16' */
  /* #20: @10 = (-@10) */
  w10 = (- w10 );
  /* #21: @17 = horzcat(@12, @10, @9, @8) */
  rr=w17;
  *rr++ = w12;
  *rr++ = w10;
  *rr++ = w9;
  *rr++ = w8;
  /* #22: @17 = @17' */
  /* #23: @18 = horzcat(@14, @15, @16, @17) */
  rr=w18;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<4; ++i) *rr++ = *cs++;
  /* #24: @12 = 0.5 */
  w12 = 5.0000000000000000e-01;
  /* #25: @3 = (@12*@3) */
  for (i=0, rr=w3, cs=w3; i<4; ++i) (*rr++)  = (w12*(*cs++));
  /* #26: @7 = mac(@18,@3,@7) */
  for (i=0, rr=w7; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w18+j, tt=w3+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #27: @14 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+6 : 0, 4, w14);
  /* #28: @12 = @14[0] */
  for (rr=(&w12), ss=w14+0; ss!=w14+1; ss+=1) *rr++ = *ss;
  /* #29: @19 = zeros(3x3) */
  casadi_clear(w19, 9);
  /* #30: @10 = 0 */
  w10 = 0.;
  /* #31: @9 = 0 */
  w9 = 0.;
  /* #32: @8 = input[2][0] */
  w8 = arg[2] ? arg[2][0] : 0;
  /* #33: @11 = input[2][1] */
  w11 = arg[2] ? arg[2][1] : 0;
  /* #34: @8 = (@8+@11) */
  w8 += w11;
  /* #35: @11 = input[2][2] */
  w11 = arg[2] ? arg[2][2] : 0;
  /* #36: @8 = (@8+@11) */
  w8 += w11;
  /* #37: @11 = input[2][3] */
  w11 = arg[2] ? arg[2][3] : 0;
  /* #38: @8 = (@8+@11) */
  w8 += w11;
  /* #39: @20 = vertcat(@10, @9, @8) */
  rr=w20;
  *rr++ = w10;
  *rr++ = w9;
  *rr++ = w8;
  /* #40: @10 = 0.68 */
  w10 = 6.8000000000000005e-01;
  /* #41: @20 = (@20/@10) */
  for (i=0, rr=w20; i<3; ++i) (*rr++) /= w10;
  /* #42: @20 = @20' */
  /* #43: @19 = mac(@2,@20,@19) */
  for (i=0, rr=w19; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w2+j, tt=w20+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #44: @21 = @19' */
  for (i=0, rr=w21, cs=w19; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #45: {@20, @22, @23} = horzsplit(@21) */
  casadi_copy(w21, 3, w20);
  casadi_copy(w21+3, 3, w22);
  casadi_copy(w21+6, 3, w23);
  /* #46: @23 = @23' */
  /* #47: {@10, @9, @8} = horzsplit(@23) */
  w10 = w23[0];
  w9 = w23[1];
  w8 = w23[2];
  /* #48: @9 = (2.*@9) */
  w9 = (2.* w9 );
  /* #49: @11 = (@12*@9) */
  w11  = (w12*w9);
  /* #50: @13 = @14[1] */
  for (rr=(&w13), ss=w14+1; ss!=w14+2; ss+=1) *rr++ = *ss;
  /* #51: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #52: @24 = (@13*@10) */
  w24  = (w13*w10);
  /* #53: @11 = (@11-@24) */
  w11 -= w24;
  /* #54: @22 = @22' */
  /* #55: {@24, @25, @26} = horzsplit(@22) */
  w24 = w22[0];
  w25 = w22[1];
  w26 = w22[2];
  /* #56: @26 = (2.*@26) */
  w26 = (2.* w26 );
  /* #57: @27 = (@12*@26) */
  w27  = (w12*w26);
  /* #58: @11 = (@11-@27) */
  w11 -= w27;
  /* #59: @27 = @14[2] */
  for (rr=(&w27), ss=w14+2; ss!=w14+3; ss+=1) *rr++ = *ss;
  /* #60: @24 = (2.*@24) */
  w24 = (2.* w24 );
  /* #61: @28 = (@27*@24) */
  w28  = (w27*w24);
  /* #62: @11 = (@11+@28) */
  w11 += w28;
  /* #63: @20 = @20' */
  /* #64: {@28, @29, @30} = horzsplit(@20) */
  w28 = w20[0];
  w29 = w20[1];
  w30 = w20[2];
  /* #65: @30 = (2.*@30) */
  w30 = (2.* w30 );
  /* #66: @31 = (@13*@30) */
  w31  = (w13*w30);
  /* #67: @11 = (@11+@31) */
  w11 += w31;
  /* #68: @29 = (2.*@29) */
  w29 = (2.* w29 );
  /* #69: @31 = (@27*@29) */
  w31  = (w27*w29);
  /* #70: @11 = (@11-@31) */
  w11 -= w31;
  /* #71: (@7[3] += @11) */
  for (rr=w7+3, ss=(&w11); rr!=w7+4; rr+=1) *rr += *ss++;
  /* #72: @11 = (2.*@12) */
  w11 = (2.* w12 );
  /* #73: @8 = (-@8) */
  w8 = (- w8 );
  /* #74: @8 = (2.*@8) */
  w8 = (2.* w8 );
  /* #75: @11 = (@11*@8) */
  w11 *= w8;
  /* #76: @31 = @14[3] */
  for (rr=(&w31), ss=w14+3; ss!=w14+4; ss+=1) *rr++ = *ss;
  /* #77: @32 = (@31*@9) */
  w32  = (w31*w9);
  /* #78: @11 = (@11+@32) */
  w11 += w32;
  /* #79: @32 = (@27*@10) */
  w32  = (w27*w10);
  /* #80: @11 = (@11+@32) */
  w11 += w32;
  /* #81: @32 = (@31*@26) */
  w32  = (w31*w26);
  /* #82: @11 = (@11-@32) */
  w11 -= w32;
  /* #83: @32 = (2.*@12) */
  w32 = (2.* w12 );
  /* #84: @25 = (-@25) */
  w25 = (- w25 );
  /* #85: @25 = (2.*@25) */
  w25 = (2.* w25 );
  /* #86: @32 = (@32*@25) */
  w32 *= w25;
  /* #87: @11 = (@11+@32) */
  w11 += w32;
  /* #88: @32 = (@13*@24) */
  w32  = (w13*w24);
  /* #89: @11 = (@11+@32) */
  w11 += w32;
  /* #90: @32 = (@27*@30) */
  w32  = (w27*w30);
  /* #91: @11 = (@11+@32) */
  w11 += w32;
  /* #92: @32 = (@13*@29) */
  w32  = (w13*w29);
  /* #93: @11 = (@11+@32) */
  w11 += w32;
  /* #94: (@7[0] += @11) */
  for (rr=w7+0, ss=(&w11); rr!=w7+1; rr+=1) *rr += *ss++;
  /* #95: @11 = (@13*@9) */
  w11  = (w13*w9);
  /* #96: @32 = (@12*@10) */
  w32  = (w12*w10);
  /* #97: @11 = (@11+@32) */
  w11 += w32;
  /* #98: @32 = (@13*@26) */
  w32  = (w13*w26);
  /* #99: @11 = (@11+@32) */
  w11 += w32;
  /* #100: @32 = (2.*@27) */
  w32 = (2.* w27 );
  /* #101: @32 = (@32*@25) */
  w32 *= w25;
  /* #102: @11 = (@11+@32) */
  w11 += w32;
  /* #103: @32 = (@31*@24) */
  w32  = (w31*w24);
  /* #104: @11 = (@11+@32) */
  w11 += w32;
  /* #105: @32 = (@12*@30) */
  w32  = (w12*w30);
  /* #106: @11 = (@11+@32) */
  w11 += w32;
  /* #107: @32 = (@31*@29) */
  w32  = (w31*w29);
  /* #108: @11 = (@11-@32) */
  w11 -= w32;
  /* #109: @32 = (2.*@27) */
  w32 = (2.* w27 );
  /* #110: @28 = (-@28) */
  w28 = (- w28 );
  /* #111: @28 = (2.*@28) */
  w28 = (2.* w28 );
  /* #112: @32 = (@32*@28) */
  w32 *= w28;
  /* #113: @11 = (@11+@32) */
  w11 += w32;
  /* #114: (@7[2] += @11) */
  for (rr=w7+2, ss=(&w11); rr!=w7+3; rr+=1) *rr += *ss++;
  /* #115: @11 = (2.*@13) */
  w11 = (2.* w13 );
  /* #116: @11 = (@11*@8) */
  w11 *= w8;
  /* #117: @9 = (@27*@9) */
  w9  = (w27*w9);
  /* #118: @11 = (@11+@9) */
  w11 += w9;
  /* #119: @10 = (@31*@10) */
  w10  = (w31*w10);
  /* #120: @11 = (@11-@10) */
  w11 -= w10;
  /* #121: @26 = (@27*@26) */
  w26  = (w27*w26);
  /* #122: @11 = (@11+@26) */
  w11 += w26;
  /* #123: @24 = (@12*@24) */
  w24  = (w12*w24);
  /* #124: @11 = (@11+@24) */
  w11 += w24;
  /* #125: @30 = (@31*@30) */
  w30  = (w31*w30);
  /* #126: @11 = (@11+@30) */
  w11 += w30;
  /* #127: @29 = (@12*@29) */
  w29  = (w12*w29);
  /* #128: @11 = (@11+@29) */
  w11 += w29;
  /* #129: @29 = (2.*@13) */
  w29 = (2.* w13 );
  /* #130: @29 = (@29*@28) */
  w29 *= w28;
  /* #131: @11 = (@11+@29) */
  w11 += w29;
  /* #132: (@7[1] += @11) */
  for (rr=w7+1, ss=(&w11); rr!=w7+2; rr+=1) *rr += *ss++;
  /* #133: output[0][1] = @7 */
  if (res[0]) casadi_copy(w7, 4, res[0]+3);
  /* #134: @20 = zeros(3x1) */
  casadi_clear(w20, 3);
  /* #135: @11 = 0.012 */
  w11 = 1.2000000000000000e-02;
  /* #136: @22 = zeros(3x1) */
  casadi_clear(w22, 3);
  /* #137: @29 = 0 */
  w29 = 0.;
  /* #138: @28 = @1[2] */
  for (rr=(&w28), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #139: @28 = (-@28) */
  w28 = (- w28 );
  /* #140: @30 = @1[1] */
  for (rr=(&w30), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #141: @23 = horzcat(@29, @28, @30) */
  rr=w23;
  *rr++ = w29;
  *rr++ = w28;
  *rr++ = w30;
  /* #142: @23 = @23' */
  /* #143: @29 = @1[2] */
  for (rr=(&w29), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #144: @28 = 0 */
  w28 = 0.;
  /* #145: @30 = @1[0] */
  for (rr=(&w30), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #146: @30 = (-@30) */
  w30 = (- w30 );
  /* #147: @33 = horzcat(@29, @28, @30) */
  rr=w33;
  *rr++ = w29;
  *rr++ = w28;
  *rr++ = w30;
  /* #148: @33 = @33' */
  /* #149: @29 = @1[1] */
  for (rr=(&w29), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #150: @29 = (-@29) */
  w29 = (- w29 );
  /* #151: @28 = @1[0] */
  for (rr=(&w28), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #152: @30 = 0 */
  w30 = 0.;
  /* #153: @34 = horzcat(@29, @28, @30) */
  rr=w34;
  *rr++ = w29;
  *rr++ = w28;
  *rr++ = w30;
  /* #154: @34 = @34' */
  /* #155: @21 = horzcat(@23, @33, @34) */
  rr=w21;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w33; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w34; i<3; ++i) *rr++ = *cs++;
  /* #156: @23 = zeros(3x1) */
  casadi_clear(w23, 3);
  /* #157: @29 = 83.3333 */
  w29 = 8.3333333333333329e+01;
  /* #158: @29 = (@29*@6) */
  w29 *= w6;
  /* #159: (@23[2] += @29) */
  for (rr=w23+2, ss=(&w29); rr!=w23+3; rr+=1) *rr += *ss++;
  /* #160: @29 = 142.857 */
  w29 = 1.4285714285714286e+02;
  /* #161: @29 = (@29*@5) */
  w29 *= w5;
  /* #162: (@23[1] += @29) */
  for (rr=w23+1, ss=(&w29); rr!=w23+2; rr+=1) *rr += *ss++;
  /* #163: @29 = 142.857 */
  w29 = 1.4285714285714286e+02;
  /* #164: @29 = (@29*@4) */
  w29 *= w4;
  /* #165: (@23[0] += @29) */
  for (rr=w23+0, ss=(&w29); rr!=w23+1; rr+=1) *rr += *ss++;
  /* #166: @33 = (-@23) */
  for (i=0, rr=w33, cs=w23; i<3; ++i) *rr++ = (- *cs++ );
  /* #167: @22 = mac(@21,@33,@22) */
  for (i=0, rr=w22; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w21+j, tt=w33+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #168: {@29, @4, @5} = vertsplit(@22) */
  w29 = w22[0];
  w4 = w22[1];
  w5 = w22[2];
  /* #169: @5 = (@11*@5) */
  w5  = (w11*w5);
  /* #170: (@20[2] += @5) */
  for (rr=w20+2, ss=(&w5); rr!=w20+3; rr+=1) *rr += *ss++;
  /* #171: @5 = 0.007 */
  w5 = 7.0000000000000001e-03;
  /* #172: @4 = (@5*@4) */
  w4  = (w5*w4);
  /* #173: (@20[1] += @4) */
  for (rr=w20+1, ss=(&w4); rr!=w20+2; rr+=1) *rr += *ss++;
  /* #174: @4 = 0.007 */
  w4 = 7.0000000000000001e-03;
  /* #175: @29 = (@4*@29) */
  w29  = (w4*w29);
  /* #176: (@20[0] += @29) */
  for (rr=w20+0, ss=(&w29); rr!=w20+1; rr+=1) *rr += *ss++;
  /* #177: @21 = zeros(3x3) */
  casadi_clear(w21, 9);
  /* #178: @29 = @1[0] */
  for (rr=(&w29), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #179: @4 = (@4*@29) */
  w4 *= w29;
  /* #180: @29 = @1[1] */
  for (rr=(&w29), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #181: @5 = (@5*@29) */
  w5 *= w29;
  /* #182: @29 = @1[2] */
  for (rr=(&w29), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #183: @11 = (@11*@29) */
  w11 *= w29;
  /* #184: @1 = vertcat(@4, @5, @11) */
  rr=w1;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w11;
  /* #185: @1 = @1' */
  /* #186: @21 = mac(@33,@1,@21) */
  for (i=0, rr=w21; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w33+j, tt=w1+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #187: @19 = @21' */
  for (i=0, rr=w19, cs=w21; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #188: {@33, @1, @22} = horzsplit(@19) */
  casadi_copy(w19, 3, w33);
  casadi_copy(w19+3, 3, w1);
  casadi_copy(w19+6, 3, w22);
  /* #189: @22 = @22' */
  /* #190: {@4, @5, NULL} = horzsplit(@22) */
  w4 = w22[0];
  w5 = w22[1];
  /* #191: (@20[0] += @5) */
  for (rr=w20+0, ss=(&w5); rr!=w20+1; rr+=1) *rr += *ss++;
  /* #192: @4 = (-@4) */
  w4 = (- w4 );
  /* #193: (@20[1] += @4) */
  for (rr=w20+1, ss=(&w4); rr!=w20+2; rr+=1) *rr += *ss++;
  /* #194: @1 = @1' */
  /* #195: {@4, NULL, @5} = horzsplit(@1) */
  w4 = w1[0];
  w5 = w1[2];
  /* #196: @5 = (-@5) */
  w5 = (- w5 );
  /* #197: (@20[0] += @5) */
  for (rr=w20+0, ss=(&w5); rr!=w20+1; rr+=1) *rr += *ss++;
  /* #198: (@20[2] += @4) */
  for (rr=w20+2, ss=(&w4); rr!=w20+3; rr+=1) *rr += *ss++;
  /* #199: @33 = @33' */
  /* #200: {NULL, @4, @5} = horzsplit(@33) */
  w4 = w33[1];
  w5 = w33[2];
  /* #201: (@20[1] += @5) */
  for (rr=w20+1, ss=(&w5); rr!=w20+2; rr+=1) *rr += *ss++;
  /* #202: @4 = (-@4) */
  w4 = (- w4 );
  /* #203: (@20[2] += @4) */
  for (rr=w20+2, ss=(&w4); rr!=w20+3; rr+=1) *rr += *ss++;
  /* #204: @18 = zeros(4x4) */
  casadi_clear(w18, 16);
  /* #205: @14 = @14' */
  /* #206: @18 = mac(@3,@14,@18) */
  for (i=0, rr=w18; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w3+j, tt=w14+i*1; k<1; ++k) *rr += ss[k*4]**tt++;
  /* #207: @35 = @18' */
  for (i=0, rr=w35, cs=w18; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #208: {@3, @14, @7, @15} = horzsplit(@35) */
  casadi_copy(w35, 4, w3);
  casadi_copy(w35+4, 4, w14);
  casadi_copy(w35+8, 4, w7);
  casadi_copy(w35+12, 4, w15);
  /* #209: @15 = @15' */
  /* #210: {@4, @5, NULL, @11} = horzsplit(@15) */
  w4 = w15[0];
  w5 = w15[1];
  w11 = w15[3];
  /* #211: @7 = @7' */
  /* #212: {@29, @6, @28, NULL} = horzsplit(@7) */
  w29 = w7[0];
  w6 = w7[1];
  w28 = w7[2];
  /* #213: @4 = (@4+@6) */
  w4 += w6;
  /* #214: @14 = @14' */
  /* #215: {NULL, @6, @30, @24} = horzsplit(@14) */
  w6 = w14[1];
  w30 = w14[2];
  w24 = w14[3];
  /* #216: @4 = (@4-@30) */
  w4 -= w30;
  /* #217: @3 = @3' */
  /* #218: {@30, NULL, @26, @10} = horzsplit(@3) */
  w30 = w3[0];
  w26 = w3[2];
  w10 = w3[3];
  /* #219: @4 = (@4-@10) */
  w4 -= w10;
  /* #220: (@20[1] += @4) */
  for (rr=w20+1, ss=(&w4); rr!=w20+2; rr+=1) *rr += *ss++;
  /* #221: @29 = (@29-@5) */
  w29 -= w5;
  /* #222: @29 = (@29+@24) */
  w29 += w24;
  /* #223: @29 = (@29-@26) */
  w29 -= w26;
  /* #224: (@20[0] += @29) */
  for (rr=w20+0, ss=(&w29); rr!=w20+1; rr+=1) *rr += *ss++;
  /* #225: @11 = (@11+@28) */
  w11 += w28;
  /* #226: @11 = (@11+@6) */
  w11 += w6;
  /* #227: @11 = (@11+@30) */
  w11 += w30;
  /* #228: (@20[2] += @11) */
  for (rr=w20+2, ss=(&w11); rr!=w20+3; rr+=1) *rr += *ss++;
  /* #229: output[0][2] = @20 */
  if (res[0]) casadi_copy(w20, 3, res[0]+7);
  /* #230: @11 = 0.1 */
  w11 = 1.0000000000000001e-01;
  /* #231: {@30, @6, @28} = vertsplit(@23) */
  w30 = w23[0];
  w6 = w23[1];
  w28 = w23[2];
  /* #232: @11 = (@11*@28) */
  w11 *= w28;
  /* #233: @28 = 0.17 */
  w28 = 1.7000000000000001e-01;
  /* #234: @28 = (@28*@6) */
  w28 *= w6;
  /* #235: @6 = (@11-@28) */
  w6  = (w11-w28);
  /* #236: @29 = 1.47059 */
  w29 = 1.4705882352941175e+00;
  /* #237: @23 = zeros(3x1) */
  casadi_clear(w23, 3);
  /* #238: @26 = 1 */
  w26 = 1.;
  /* #239: @24 = sq(@13) */
  w24 = casadi_sq( w13 );
  /* #240: @5 = sq(@27) */
  w5 = casadi_sq( w27 );
  /* #241: @24 = (@24+@5) */
  w24 += w5;
  /* #242: @24 = (2.*@24) */
  w24 = (2.* w24 );
  /* #243: @26 = (@26-@24) */
  w26 -= w24;
  /* #244: @24 = (@12*@13) */
  w24  = (w12*w13);
  /* #245: @5 = (@31*@27) */
  w5  = (w31*w27);
  /* #246: @24 = (@24-@5) */
  w24 -= w5;
  /* #247: @24 = (2.*@24) */
  w24 = (2.* w24 );
  /* #248: @5 = (@12*@27) */
  w5  = (w12*w27);
  /* #249: @4 = (@31*@13) */
  w4  = (w31*w13);
  /* #250: @5 = (@5+@4) */
  w5 += w4;
  /* #251: @5 = (2.*@5) */
  w5 = (2.* w5 );
  /* #252: @20 = horzcat(@26, @24, @5) */
  rr=w20;
  *rr++ = w26;
  *rr++ = w24;
  *rr++ = w5;
  /* #253: @20 = @20' */
  /* #254: @26 = (@13*@12) */
  w26  = (w13*w12);
  /* #255: @24 = (@31*@27) */
  w24  = (w31*w27);
  /* #256: @26 = (@26+@24) */
  w26 += w24;
  /* #257: @26 = (2.*@26) */
  w26 = (2.* w26 );
  /* #258: @24 = 1 */
  w24 = 1.;
  /* #259: @5 = sq(@12) */
  w5 = casadi_sq( w12 );
  /* #260: @4 = sq(@27) */
  w4 = casadi_sq( w27 );
  /* #261: @5 = (@5+@4) */
  w5 += w4;
  /* #262: @5 = (2.*@5) */
  w5 = (2.* w5 );
  /* #263: @24 = (@24-@5) */
  w24 -= w5;
  /* #264: @5 = (@13*@27) */
  w5  = (w13*w27);
  /* #265: @4 = (@31*@12) */
  w4  = (w31*w12);
  /* #266: @5 = (@5-@4) */
  w5 -= w4;
  /* #267: @5 = (2.*@5) */
  w5 = (2.* w5 );
  /* #268: @33 = horzcat(@26, @24, @5) */
  rr=w33;
  *rr++ = w26;
  *rr++ = w24;
  *rr++ = w5;
  /* #269: @33 = @33' */
  /* #270: @26 = (@27*@12) */
  w26  = (w27*w12);
  /* #271: @24 = (@31*@13) */
  w24  = (w31*w13);
  /* #272: @26 = (@26-@24) */
  w26 -= w24;
  /* #273: @26 = (2.*@26) */
  w26 = (2.* w26 );
  /* #274: @27 = (@27*@13) */
  w27 *= w13;
  /* #275: @31 = (@31*@12) */
  w31 *= w12;
  /* #276: @27 = (@27+@31) */
  w27 += w31;
  /* #277: @27 = (2.*@27) */
  w27 = (2.* w27 );
  /* #278: @31 = 1 */
  w31 = 1.;
  /* #279: @12 = sq(@12) */
  w12 = casadi_sq( w12 );
  /* #280: @13 = sq(@13) */
  w13 = casadi_sq( w13 );
  /* #281: @12 = (@12+@13) */
  w12 += w13;
  /* #282: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #283: @31 = (@31-@12) */
  w31 -= w12;
  /* #284: @1 = horzcat(@26, @27, @31) */
  rr=w1;
  *rr++ = w26;
  *rr++ = w27;
  *rr++ = w31;
  /* #285: @1 = @1' */
  /* #286: @19 = horzcat(@20, @33, @1) */
  rr=w19;
  for (i=0, cs=w20; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w33; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w1; i<3; ++i) *rr++ = *cs++;
  /* #287: @23 = mac(@19,@2,@23) */
  for (i=0, rr=w23; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w19+j, tt=w2+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #288: @23 = (@29*@23) */
  for (i=0, rr=w23, cs=w23; i<3; ++i) (*rr++)  = (w29*(*cs++));
  /* #289: {NULL, NULL, @29} = vertsplit(@23) */
  w29 = w23[2];
  /* #290: @6 = (@6+@29) */
  w6 += w29;
  /* #291: output[0][3] = @6 */
  if (res[0]) res[0][10] = w6;
  /* #292: @6 = 0.17 */
  w6 = 1.7000000000000001e-01;
  /* #293: @6 = (@6*@30) */
  w6 *= w30;
  /* #294: @30 = (@6-@11) */
  w30  = (w6-w11);
  /* #295: @30 = (@30+@29) */
  w30 += w29;
  /* #296: output[0][4] = @30 */
  if (res[0]) res[0][11] = w30;
  /* #297: @28 = (@11+@28) */
  w28  = (w11+w28);
  /* #298: @28 = (@28+@29) */
  w28 += w29;
  /* #299: output[0][5] = @28 */
  if (res[0]) res[0][12] = w28;
  /* #300: @6 = (-@6) */
  w6 = (- w6 );
  /* #301: @6 = (@6-@11) */
  w6 -= w11;
  /* #302: @6 = (@6+@29) */
  w6 += w29;
  /* #303: output[0][6] = @6 */
  if (res[0]) res[0][13] = w6;
  return 0;
}

CASADI_SYMBOL_EXPORT int Quadrotor_model_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Quadrotor_model_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Quadrotor_model_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Quadrotor_model_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Quadrotor_model_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Quadrotor_model_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Quadrotor_model_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void Quadrotor_model_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Quadrotor_model_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Quadrotor_model_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Quadrotor_model_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Quadrotor_model_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Quadrotor_model_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Quadrotor_model_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Quadrotor_model_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Quadrotor_model_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 7;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 130;
  return 0;
}

CASADI_SYMBOL_EXPORT int Quadrotor_model_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 7*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 130*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
