/* This file was automatically generated by CasADi 3.6.5.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Quadrotor_model_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {0, 0, 0};

static const casadi_real casadi_c0[3] = {0., 0., -9.8100000000000005e+00};

/* Quadrotor_model_expl_ode_fun:(i0[13],i1[4],i2[])->(o0[13]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real *w0=w+4, w1, *w2=w+8, w3, w4, w5, w6, *w7=w+16, *w8=w+19, *w9=w+22, *w10=w+25, *w11=w+34, w12, w13, *w14=w+45, w15, w16, *w17=w+51, *w18=w+55, *w19=w+59, *w20=w+63, *w21=w+67, *w22=w+83, *w23=w+99, *w24=w+102;
  /* #0: @0 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 3, w0);
  /* #1: output[0][0] = @0 */
  casadi_copy(w0, 3, res[0]);
  /* #2: @0 = zeros(3x1) */
  casadi_clear(w0, 3);
  /* #3: @1 = 1 */
  w1 = 1.;
  /* #4: @2 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+6 : 0, 4, w2);
  /* #5: @3 = @2[1] */
  for (rr=(&w3), ss=w2+1; ss!=w2+2; ss+=1) *rr++ = *ss;
  /* #6: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #7: @4 = @2[2] */
  for (rr=(&w4), ss=w2+2; ss!=w2+3; ss+=1) *rr++ = *ss;
  /* #8: @4 = sq(@4) */
  w4 = casadi_sq( w4 );
  /* #9: @3 = (@3+@4) */
  w3 += w4;
  /* #10: @3 = (2.*@3) */
  w3 = (2.* w3 );
  /* #11: @1 = (@1-@3) */
  w1 -= w3;
  /* #12: @3 = @2[0] */
  for (rr=(&w3), ss=w2+0; ss!=w2+1; ss+=1) *rr++ = *ss;
  /* #13: @4 = @2[1] */
  for (rr=(&w4), ss=w2+1; ss!=w2+2; ss+=1) *rr++ = *ss;
  /* #14: @3 = (@3*@4) */
  w3 *= w4;
  /* #15: @4 = @2[3] */
  for (rr=(&w4), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #16: @5 = @2[2] */
  for (rr=(&w5), ss=w2+2; ss!=w2+3; ss+=1) *rr++ = *ss;
  /* #17: @4 = (@4*@5) */
  w4 *= w5;
  /* #18: @3 = (@3-@4) */
  w3 -= w4;
  /* #19: @3 = (2.*@3) */
  w3 = (2.* w3 );
  /* #20: @4 = @2[0] */
  for (rr=(&w4), ss=w2+0; ss!=w2+1; ss+=1) *rr++ = *ss;
  /* #21: @5 = @2[2] */
  for (rr=(&w5), ss=w2+2; ss!=w2+3; ss+=1) *rr++ = *ss;
  /* #22: @4 = (@4*@5) */
  w4 *= w5;
  /* #23: @5 = @2[3] */
  for (rr=(&w5), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #24: @6 = @2[1] */
  for (rr=(&w6), ss=w2+1; ss!=w2+2; ss+=1) *rr++ = *ss;
  /* #25: @5 = (@5*@6) */
  w5 *= w6;
  /* #26: @4 = (@4+@5) */
  w4 += w5;
  /* #27: @4 = (2.*@4) */
  w4 = (2.* w4 );
  /* #28: @7 = horzcat(@1, @3, @4) */
  rr=w7;
  *rr++ = w1;
  *rr++ = w3;
  *rr++ = w4;
  /* #29: @7 = @7' */
  /* #30: @1 = @2[0] */
  for (rr=(&w1), ss=w2+0; ss!=w2+1; ss+=1) *rr++ = *ss;
  /* #31: @3 = @2[1] */
  for (rr=(&w3), ss=w2+1; ss!=w2+2; ss+=1) *rr++ = *ss;
  /* #32: @1 = (@1*@3) */
  w1 *= w3;
  /* #33: @3 = @2[3] */
  for (rr=(&w3), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #34: @4 = @2[2] */
  for (rr=(&w4), ss=w2+2; ss!=w2+3; ss+=1) *rr++ = *ss;
  /* #35: @3 = (@3*@4) */
  w3 *= w4;
  /* #36: @1 = (@1+@3) */
  w1 += w3;
  /* #37: @1 = (2.*@1) */
  w1 = (2.* w1 );
  /* #38: @3 = 1 */
  w3 = 1.;
  /* #39: @4 = @2[0] */
  for (rr=(&w4), ss=w2+0; ss!=w2+1; ss+=1) *rr++ = *ss;
  /* #40: @4 = sq(@4) */
  w4 = casadi_sq( w4 );
  /* #41: @5 = @2[2] */
  for (rr=(&w5), ss=w2+2; ss!=w2+3; ss+=1) *rr++ = *ss;
  /* #42: @5 = sq(@5) */
  w5 = casadi_sq( w5 );
  /* #43: @4 = (@4+@5) */
  w4 += w5;
  /* #44: @4 = (2.*@4) */
  w4 = (2.* w4 );
  /* #45: @3 = (@3-@4) */
  w3 -= w4;
  /* #46: @4 = @2[1] */
  for (rr=(&w4), ss=w2+1; ss!=w2+2; ss+=1) *rr++ = *ss;
  /* #47: @5 = @2[2] */
  for (rr=(&w5), ss=w2+2; ss!=w2+3; ss+=1) *rr++ = *ss;
  /* #48: @4 = (@4*@5) */
  w4 *= w5;
  /* #49: @5 = @2[3] */
  for (rr=(&w5), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #50: @6 = @2[0] */
  for (rr=(&w6), ss=w2+0; ss!=w2+1; ss+=1) *rr++ = *ss;
  /* #51: @5 = (@5*@6) */
  w5 *= w6;
  /* #52: @4 = (@4-@5) */
  w4 -= w5;
  /* #53: @4 = (2.*@4) */
  w4 = (2.* w4 );
  /* #54: @8 = horzcat(@1, @3, @4) */
  rr=w8;
  *rr++ = w1;
  *rr++ = w3;
  *rr++ = w4;
  /* #55: @8 = @8' */
  /* #56: @1 = @2[0] */
  for (rr=(&w1), ss=w2+0; ss!=w2+1; ss+=1) *rr++ = *ss;
  /* #57: @3 = @2[2] */
  for (rr=(&w3), ss=w2+2; ss!=w2+3; ss+=1) *rr++ = *ss;
  /* #58: @1 = (@1*@3) */
  w1 *= w3;
  /* #59: @3 = @2[3] */
  for (rr=(&w3), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #60: @4 = @2[1] */
  for (rr=(&w4), ss=w2+1; ss!=w2+2; ss+=1) *rr++ = *ss;
  /* #61: @3 = (@3*@4) */
  w3 *= w4;
  /* #62: @1 = (@1-@3) */
  w1 -= w3;
  /* #63: @1 = (2.*@1) */
  w1 = (2.* w1 );
  /* #64: @3 = @2[1] */
  for (rr=(&w3), ss=w2+1; ss!=w2+2; ss+=1) *rr++ = *ss;
  /* #65: @4 = @2[2] */
  for (rr=(&w4), ss=w2+2; ss!=w2+3; ss+=1) *rr++ = *ss;
  /* #66: @3 = (@3*@4) */
  w3 *= w4;
  /* #67: @4 = @2[3] */
  for (rr=(&w4), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #68: @5 = @2[0] */
  for (rr=(&w5), ss=w2+0; ss!=w2+1; ss+=1) *rr++ = *ss;
  /* #69: @4 = (@4*@5) */
  w4 *= w5;
  /* #70: @3 = (@3+@4) */
  w3 += w4;
  /* #71: @3 = (2.*@3) */
  w3 = (2.* w3 );
  /* #72: @4 = 1 */
  w4 = 1.;
  /* #73: @5 = @2[0] */
  for (rr=(&w5), ss=w2+0; ss!=w2+1; ss+=1) *rr++ = *ss;
  /* #74: @5 = sq(@5) */
  w5 = casadi_sq( w5 );
  /* #75: @6 = @2[1] */
  for (rr=(&w6), ss=w2+1; ss!=w2+2; ss+=1) *rr++ = *ss;
  /* #76: @6 = sq(@6) */
  w6 = casadi_sq( w6 );
  /* #77: @5 = (@5+@6) */
  w5 += w6;
  /* #78: @5 = (2.*@5) */
  w5 = (2.* w5 );
  /* #79: @4 = (@4-@5) */
  w4 -= w5;
  /* #80: @9 = horzcat(@1, @3, @4) */
  rr=w9;
  *rr++ = w1;
  *rr++ = w3;
  *rr++ = w4;
  /* #81: @9 = @9' */
  /* #82: @10 = horzcat(@7, @8, @9) */
  rr=w10;
  for (i=0, cs=w7; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w8; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w9; i<3; ++i) *rr++ = *cs++;
  /* #83: @11 = @10' */
  for (i=0, rr=w11, cs=w10; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #84: @1 = 0 */
  w1 = 0.;
  /* #85: @3 = 0 */
  w3 = 0.;
  /* #86: @4 = input[1][0] */
  w4 = arg[1] ? arg[1][0] : 0;
  /* #87: @5 = input[1][1] */
  w5 = arg[1] ? arg[1][1] : 0;
  /* #88: @6 = (@4+@5) */
  w6  = (w4+w5);
  /* #89: @12 = input[1][2] */
  w12 = arg[1] ? arg[1][2] : 0;
  /* #90: @6 = (@6+@12) */
  w6 += w12;
  /* #91: @13 = input[1][3] */
  w13 = arg[1] ? arg[1][3] : 0;
  /* #92: @6 = (@6+@13) */
  w6 += w13;
  /* #93: @7 = vertcat(@1, @3, @6) */
  rr=w7;
  *rr++ = w1;
  *rr++ = w3;
  *rr++ = w6;
  /* #94: @1 = 0.68 */
  w1 = 6.8000000000000005e-01;
  /* #95: @7 = (@7/@1) */
  for (i=0, rr=w7; i<3; ++i) (*rr++) /= w1;
  /* #96: @0 = mac(@11,@7,@0) */
  for (i=0, rr=w0; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w11+j, tt=w7+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #97: @7 = [0, 0, -9.81] */
  casadi_copy(casadi_c0, 3, w7);
  /* #98: @0 = (@0-@7) */
  for (i=0, rr=w0, cs=w7; i<3; ++i) (*rr++) -= (*cs++);
  /* #99: output[0][1] = @0 */
  if (res[0]) casadi_copy(w0, 3, res[0]+3);
  /* #100: @1 = 0.5 */
  w1 = 5.0000000000000000e-01;
  /* #101: @14 = zeros(4x1) */
  casadi_clear(w14, 4);
  /* #102: @3 = 0 */
  w3 = 0.;
  /* #103: @0 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+10 : 0, 3, w0);
  /* #104: @6 = @0[0] */
  for (rr=(&w6), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #105: @6 = (-@6) */
  w6 = (- w6 );
  /* #106: @15 = @0[2] */
  for (rr=(&w15), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #107: @15 = (-@15) */
  w15 = (- w15 );
  /* #108: @16 = 0 */
  w16 = 0.;
  /* #109: @17 = horzcat(@3, @6, @15, @16) */
  rr=w17;
  *rr++ = w3;
  *rr++ = w6;
  *rr++ = w15;
  *rr++ = w16;
  /* #110: @17 = @17' */
  /* #111: @3 = @0[0] */
  for (rr=(&w3), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #112: @6 = 0 */
  w6 = 0.;
  /* #113: @15 = @0[2] */
  for (rr=(&w15), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #114: @15 = (-@15) */
  w15 = (- w15 );
  /* #115: @16 = @0[1] */
  for (rr=(&w16), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #116: @18 = horzcat(@3, @6, @15, @16) */
  rr=w18;
  *rr++ = w3;
  *rr++ = w6;
  *rr++ = w15;
  *rr++ = w16;
  /* #117: @18 = @18' */
  /* #118: @3 = @0[1] */
  for (rr=(&w3), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #119: @6 = @0[2] */
  for (rr=(&w6), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #120: @15 = 0 */
  w15 = 0.;
  /* #121: @16 = @0[0] */
  for (rr=(&w16), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #122: @16 = (-@16) */
  w16 = (- w16 );
  /* #123: @19 = horzcat(@3, @6, @15, @16) */
  rr=w19;
  *rr++ = w3;
  *rr++ = w6;
  *rr++ = w15;
  *rr++ = w16;
  /* #124: @19 = @19' */
  /* #125: @3 = @0[2] */
  for (rr=(&w3), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #126: @6 = @0[1] */
  for (rr=(&w6), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #127: @6 = (-@6) */
  w6 = (- w6 );
  /* #128: @15 = @0[0] */
  for (rr=(&w15), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #129: @16 = 0 */
  w16 = 0.;
  /* #130: @20 = horzcat(@3, @6, @15, @16) */
  rr=w20;
  *rr++ = w3;
  *rr++ = w6;
  *rr++ = w15;
  *rr++ = w16;
  /* #131: @20 = @20' */
  /* #132: @21 = horzcat(@17, @18, @19, @20) */
  rr=w21;
  for (i=0, cs=w17; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<4; ++i) *rr++ = *cs++;
  /* #133: @22 = @21' */
  for (i=0, rr=w22, cs=w21; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #134: @14 = mac(@22,@2,@14) */
  for (i=0, rr=w14; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w22+j, tt=w2+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #135: @14 = (@1*@14) */
  for (i=0, rr=w14, cs=w14; i<4; ++i) (*rr++)  = (w1*(*cs++));
  /* #136: output[0][2] = @14 */
  if (res[0]) casadi_copy(w14, 4, res[0]+6);
  /* #137: @1 = 142.857 */
  w1 = 1.4285714285714286e+02;
  /* #138: @3 = 0.2 */
  w3 = 2.0000000000000001e-01;
  /* #139: @6 = (@5-@13) */
  w6  = (w5-w13);
  /* #140: @3 = (@3*@6) */
  w3 *= w6;
  /* #141: @6 = 0.2 */
  w6 = 2.0000000000000001e-01;
  /* #142: @15 = (@12-@4) */
  w15  = (w12-w4);
  /* #143: @6 = (@6*@15) */
  w6 *= w15;
  /* #144: @4 = (@4-@5) */
  w4 -= w5;
  /* #145: @4 = (@4+@12) */
  w4 += w12;
  /* #146: @4 = (@4-@13) */
  w4 -= w13;
  /* #147: @7 = vertcat(@3, @6, @4) */
  rr=w7;
  *rr++ = w3;
  *rr++ = w6;
  *rr++ = w4;
  /* #148: @8 = zeros(3x1) */
  casadi_clear(w8, 3);
  /* #149: @3 = 0 */
  w3 = 0.;
  /* #150: @6 = @0[2] */
  for (rr=(&w6), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #151: @6 = (-@6) */
  w6 = (- w6 );
  /* #152: @4 = @0[1] */
  for (rr=(&w4), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #153: @9 = horzcat(@3, @6, @4) */
  rr=w9;
  *rr++ = w3;
  *rr++ = w6;
  *rr++ = w4;
  /* #154: @9 = @9' */
  /* #155: @3 = @0[2] */
  for (rr=(&w3), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #156: @6 = 0 */
  w6 = 0.;
  /* #157: @4 = @0[0] */
  for (rr=(&w4), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #158: @4 = (-@4) */
  w4 = (- w4 );
  /* #159: @23 = horzcat(@3, @6, @4) */
  rr=w23;
  *rr++ = w3;
  *rr++ = w6;
  *rr++ = w4;
  /* #160: @23 = @23' */
  /* #161: @3 = @0[1] */
  for (rr=(&w3), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #162: @3 = (-@3) */
  w3 = (- w3 );
  /* #163: @6 = @0[0] */
  for (rr=(&w6), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #164: @4 = 0 */
  w4 = 0.;
  /* #165: @24 = horzcat(@3, @6, @4) */
  rr=w24;
  *rr++ = w3;
  *rr++ = w6;
  *rr++ = w4;
  /* #166: @24 = @24' */
  /* #167: @11 = horzcat(@9, @23, @24) */
  rr=w11;
  for (i=0, cs=w9; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w24; i<3; ++i) *rr++ = *cs++;
  /* #168: @10 = @11' */
  for (i=0, rr=w10, cs=w11; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #169: @3 = 0.007 */
  w3 = 7.0000000000000001e-03;
  /* #170: @6 = @0[0] */
  for (rr=(&w6), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #171: @3 = (@3*@6) */
  w3 *= w6;
  /* #172: @6 = 0.007 */
  w6 = 7.0000000000000001e-03;
  /* #173: @4 = @0[1] */
  for (rr=(&w4), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #174: @6 = (@6*@4) */
  w6 *= w4;
  /* #175: @4 = 0.012 */
  w4 = 1.2000000000000000e-02;
  /* #176: @13 = @0[2] */
  for (rr=(&w13), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #177: @4 = (@4*@13) */
  w4 *= w13;
  /* #178: @0 = vertcat(@3, @6, @4) */
  rr=w0;
  *rr++ = w3;
  *rr++ = w6;
  *rr++ = w4;
  /* #179: @8 = mac(@10,@0,@8) */
  for (i=0, rr=w8; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w10+j, tt=w0+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #180: @7 = (@7-@8) */
  for (i=0, rr=w7, cs=w8; i<3; ++i) (*rr++) -= (*cs++);
  /* #181: @3 = @7[0] */
  for (rr=(&w3), ss=w7+0; ss!=w7+1; ss+=1) *rr++ = *ss;
  /* #182: @1 = (@1*@3) */
  w1 *= w3;
  /* #183: output[0][3] = @1 */
  if (res[0]) res[0][10] = w1;
  /* #184: @1 = 142.857 */
  w1 = 1.4285714285714286e+02;
  /* #185: @3 = @7[1] */
  for (rr=(&w3), ss=w7+1; ss!=w7+2; ss+=1) *rr++ = *ss;
  /* #186: @1 = (@1*@3) */
  w1 *= w3;
  /* #187: output[0][4] = @1 */
  if (res[0]) res[0][11] = w1;
  /* #188: @1 = 83.3333 */
  w1 = 8.3333333333333329e+01;
  /* #189: @3 = @7[2] */
  for (rr=(&w3), ss=w7+2; ss!=w7+3; ss+=1) *rr++ = *ss;
  /* #190: @1 = (@1*@3) */
  w1 *= w3;
  /* #191: output[0][5] = @1 */
  if (res[0]) res[0][12] = w1;
  return 0;
}

CASADI_SYMBOL_EXPORT int Quadrotor_model_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Quadrotor_model_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Quadrotor_model_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Quadrotor_model_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Quadrotor_model_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Quadrotor_model_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Quadrotor_model_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void Quadrotor_model_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Quadrotor_model_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int Quadrotor_model_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Quadrotor_model_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Quadrotor_model_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Quadrotor_model_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Quadrotor_model_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Quadrotor_model_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Quadrotor_model_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 105;
  return 0;
}

CASADI_SYMBOL_EXPORT int Quadrotor_model_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 105*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
